Update intersection model map msgs
usdot-fhwa-stol/carma-streets pull request #144
Opened 2022-06-04 02:10 UTC by dan-du-car

# PR Details
## Description
Standup Kafka client to consume MAP msgs or Setup configurations to: 

Include MAP information in intersection geometry

Describe relationship between MAP and Lanelet2 information (Lane IDs)

Integration test intersection_model  with service that uses intersection_client

## Related Issue
NA

## Motivation and Context
UC3

## How Has This Been Tested?
local integration and unit test

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
[CARMA Contributing Guide](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) 
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-06-06 21:52 UTC, paulbourelly999 commented on intersection_model/include/intersection_model.h
> +            void mapping_lanelet_id_2_lane_id(const map_referencepoint& ref_point, const map_lane& lane, const std::vector<lanelet::ConstLanelet>& subj_lanelets, std::unordered_map<long,lanelet::Cons
Needs a java-doc comment

2022-06-06 22:57 UTC, dan-du-car commented on intersection_model/include/intersection_model.h
> +            void mapping_lanelet_id_2_lane_id(const map_referencepoint& ref_point, const map_lane& lane, const std::vector<lanelet::ConstLanelet>& subj_lanelets, std::unordered_map<long,lanelet::Cons
Addressed

2022-06-07 17:42 UTC, paulbourelly999 commented on intersection_model/include/intersection_model.h
> +             * @param y coordinate
Units?

2022-06-07 17:49 UTC, paulbourelly999 commented on intersection_model/test/test_intersection_model.cpp
> +TEST(intersection_model_test, find_link_lanelet_id_by_enter_depart_lanelet_ids)
Brief comments to describe test case might be useful.

2022-06-07 18:59 UTC, dan-du-car commented on intersection_model/test/test_intersection_model.cpp
> +TEST(intersection_model_test, find_link_lanelet_id_by_enter_depart_lanelet_ids)
The test case should verify the function. The description/java-doc comments are located  where the function declared. Not needed here.

2022-06-07 19:02 UTC, dan-du-car commented on intersection_model/include/intersection_model.h
> +             * @param y coordinate
Addressed https://github.com/usdot-fhwa-stol/carma-streets/pull/144/commits/cf53ef6fcb506240d00e4e1cc7d81411a66d6d94

2022-06-08 01:38 UTC, paulbourelly999 commented on intersection_model/include/map_msg_worker.h
> +        // Kafka consumer configuration
So implement MAP message processing for kafka is awesome but kind of makes more work for us in comparison to just implementing reading a MAP file. This is because it means we will have to write additional code in the CARMA-Streets plugin to send MAP messages to kafka on startup. I don't want to necessary abandon any work you have already done here but it may be worth while to just implement it as file reading now so we don't have to do anything on V2X-Hub. What do you think?

2022-06-08 01:40 UTC, paulbourelly999 commented on intersection_model/include/map_msg_worker.h
> +        map_msg_worker(const int intersection_id, const std::string &bootstrap_server, const std::string &map_msg_group_id, const std::string &map_msg_topic_name);
Probably want to add comments describing these constructor parameters.

2022-06-08 13:40 UTC, paulbourelly999 commented on intersection_model/include/intersection_model.h
>          int32_t signal_group_id         = 0;    //0 = Not available
Should we have comments describing what this property is?

2022-06-08 13:42 UTC, dan-du-car commented on intersection_model/include/intersection_model.h
>          int32_t signal_group_id         = 0;    //0 = Not available
It is self-explanatory.

2022-06-08 13:43 UTC, paulbourelly999 commented on intersection_model/include/intersection_model.h
> +            std::vector<lanelet_info_t> get_conflict_lanelets_info(int64_t sub_link_lanelet_id);
Why do we return all other lanelet vectors as constant references except this one.

2022-06-08 13:43 UTC, paulbourelly999 commented on intersection_model/include/intersection_model.h
> +            std::vector<lanelet_info_t> get_conflict_lanelets_info(int64_t sub_link_lanelet_id);
Also should this method be constant

2022-06-08 13:52 UTC, dan-du-car commented on intersection_model/include/intersection_model.h
> +            bool update_link_departure_lanelets_info_by_entry_lanelet(const lanelet::Lanelet &entry_lanelet);
Addressed

2022-06-08 13:55 UTC, paulbourelly999 commented on intersection_model/include/intersection_model.h
> +            /**
Is a line string the same as a list or points that form a line?

2022-06-08 13:56 UTC, dan-du-car commented on intersection_model/include/intersection_model.h
> +             * @param ref_point Reference location (latitude, longitude, elevation) of the subsequent data points
Reference location (latitude, longitude, elevation) of the subsequent data points

2022-06-08 13:56 UTC, dan-du-car commented on intersection_model/include/intersection_model.h
> +            /**
yes

2022-06-08 19:10 UTC, paulbourelly999 commented on intersection_model/src/intersection_model.cpp
> +        SPDLOG_INFO("Intersection id {0} has {1} number of geometries.", int_map_msg->intersectionid, int_map_msg->geometries.size());
Does one geometry correspond to one intersection are is that something different.

2022-06-08 19:23 UTC, paulbourelly999 commented on intersection_model/src/map_msg_worker.cpp
> +        if (!doc.HasParseError() && doc.FindMember("map_data")->value.IsObject())
I don't want to create extra work for you here but in the future we should probably split this parsing logic into different helper methods so that we don't have  so many nested if/for/try blocks. This would make the logic easier to read and maintain in my opinion.  I think for the MAP message its fine right now but in the future it would be nice to have more readable parsing logic.

2022-06-08 19:26 UTC, dan-du-car commented on intersection_model/src/map_msg_worker.cpp
> +        if (!doc.HasParseError() && doc.FindMember("map_data")->value.IsObject())
That might be a good idea

2022-06-08 20:22 UTC, paulbourelly999 commented on intersection_model/src/server/src/main.cpp
> +void intersection_model_event_update(std::shared_ptr<intersection_model::intersection_model> model, std::shared_ptr<intersection_model::map_msg_worker> map_msp_worker)
We probably want to add intersection_model/server/src into sonar properties as a source code location for intersection_model. It wasn't previously there since it use to hold generated could but now this is custom code so we probably want sonar-scanner analysis.

2022-06-08 20:25 UTC, paulbourelly999 commented on intersection_model/include/intersection_model.h
> +            const std::vector<int> get_shared_entry_link_lanelet_ids(int64_t subject_link_lanelet_id);
This should be a constant method too right?

2022-06-08 20:28 UTC, dan-du-car commented on intersection_model/include/intersection_model.h
> +            const std::vector<int> get_shared_entry_link_lanelet_ids(int64_t subject_link_lanelet_id);
Addressed

2022-06-08 20:29 UTC, dan-du-car commented on intersection_model/src/server/src/main.cpp
> +void intersection_model_event_update(std::shared_ptr<intersection_model::intersection_model> model, std::shared_ptr<intersection_model::map_msg_worker> map_msp_worker)
I think the top package level should allow the sonar scanner to scan the subsequent folders. If that is not the case, how and where exactly you want to update this?

2022-06-08 20:48 UTC, dan-du-car commented on intersection_model/include/intersection_model.h
> +            const std::vector<int> get_shared_entry_link_lanelet_ids(int64_t subject_link_lanelet_id);
It seems that it is actually updating the object. so it cannot be a const method.

2022-06-08 20:57 UTC, paulbourelly999 commented on intersection_model/src/intersection_model.cpp
> +            cur_x += static_cast<double>(node.x) * CM_TO_M;
So each note in the map is a relative location to the first reference node. Is that correct. Maybe some in line comments might help make that clear.

2022-06-08 21:00 UTC, paulbourelly999 commented on intersection_model/src/intersection_model.cpp
> +        std::unordered_map<lanelet::Id, double> lanelet2lane_path_distance_m;
This is a map of lanelet ids and average distance from the basic_points line. Is that correct?

2022-06-08 21:11 UTC, paulbourelly999 commented on intersection_model/src/intersection_model.cpp
> +                lane2lanelet_m.insert({lane.lane_id, subj_l});
What does insert method for a ConstLanelet do?

2022-06-08 21:36 UTC, dan-du-car commented on intersection_model/src/intersection_model.cpp
> +                lane2lanelet_m.insert({lane.lane_id, subj_l});
It is inserting into constlanelet.

2022-06-08 21:41 UTC, dan-du-car commented on intersection_model/src/intersection_model.cpp
> +                lane2lanelet_m.insert({lane.lane_id, subj_l});
The std::map value is const as we are not modifying it at the caller

2022-06-08 21:45 UTC, dan-du-car commented on intersection_model/src/intersection_model.cpp
> +        const auto&  min_distance_pair = std::min_element(lanelet2lane_path_distance_m.begin(), lanelet2lane_path_distance_m.end(), [](const auto& l, const auto& r){return l.second < r.second; });
I think this is a valid point. I am updating it to consider to lane width as well

2022-06-08 23:44 UTC, dan-du-car commented on intersection_model/src/intersection_model.cpp
> +        const auto&  min_distance_pair = std::min_element(lanelet2lane_path_distance_m.begin(), lanelet2lane_path_distance_m.end(), [](const auto& l, const auto& r){return l.second < r.second; });
https://github.com/usdot-fhwa-stol/carma-streets/pull/144/commits/863096c4a1b7f5e056295a86aa5fb0c40ef70443

2022-06-09 03:29 UTC, paulbourelly999 commented on intersection_model/src/intersection_model.cpp
> +        std::unordered_map<long, lanelet::ConstLanelet> entry_lane2lanelet_m;
What are these maps for. I see one seems to be entry lanes objects to lane ids from the map.

2022-06-09 03:41 UTC, paulbourelly999 commented on intersection_model/include/intersection_model.h
> +            void mapping_lane_id_2_lanelet_id(const map_referencepoint& ref_point, const map_lane& lane, const long lane_width, const std::vector<lanelet::ConstLanelet>& subj_lanelets, std::unordered
Since this method is returning values by reference ( I mean its update/populating the param lane2lanelet_m and passing it back by reference. It might be helpful to state what the incoming condition of this map is expected to be and what the method does to populate it.

2022-06-09 03:44 UTC, paulbourelly999 commented on intersection_model/src/intersection_model.cpp
> +        std::unordered_map<long, map_lane> link_departure_lanes_m;
Are all map lane objects the equivalent of departure lanes from the j2735 MAP?

2022-06-09 03:48 UTC, paulbourelly999 commented on intersection_model/src/intersection_model.cpp
> +        std::vector<signalized_intersection_lanelets> enter_departure_lanelets2SG_id_v;
Are you mapping signal Group id to a pair of entry/departure lanelets rather than the link lanelet that connects them here. I am a little confused.

2022-06-09 03:57 UTC, paulbourelly999 commented on intersection_model/src/intersection_model.cpp
> +        });
Ok if I understand the logic correctly in this method, you are first finding the mapping between entry lane and entry lanelet using the center line provided by the J2735 MAP message and calculating an average distance from the entry-lanelet center line ( I saw you implemented lane width but it still looks like there is no minimum threshold so if the closest entry lanelet has an average distance of 10,000 m you still assign it. Then you map departure lanes to departure lanelets. Then you use these mappings to create a map of entry/departure lanelets to signal groups and from there you pass the information to the connecting lanelets. 

I assume you do this because the MAP message only describes enter or approach lanes and not connecting lanes geometry. Is any of this accurate.

2022-06-09 04:05 UTC, paulbourelly999 requested changes
I think I am largely fine with this review. One thing that would make this more understandable accompanying any maps or collections you set up in methods with a description of their purpose. Also for any methods that are pass by reference and change the value of the reference, it would help if inline and method comments reflected the intention of what you are changing and maybe some information about what is assumed about the input. All together this looks very good. I left some comments about the lane to lanelet mapping method since it seems to just map each lane to its closest lanelet regardless of how large a distance we find in between them. If we did have MAP and osm files that have the same intersection name but represent different locations it seems you implementation would read them and map them despite large average distances between them. Might be reasonable to throw and exception if the lowest average distance between the two centerlines exceeds 5 meter or something (Maybe even a larger value) but we can put this off as an improvement if you think that is better.  I am ok merging this as soon as you just update the method comments that modify reference and add some inline comments for the unordered maps you create and what they are for.

2022-06-09 13:44 UTC, dan-du-car commented on intersection_model/src/intersection_model.cpp
> +        std::unordered_map<long, lanelet::ConstLanelet> entry_lane2lanelet_m;
Please refer to J2735 MAP message definition. This is streets version map to mimic that.

2022-06-09 13:47 UTC, dan-du-car commented on intersection_model/include/intersection_model.h
> +            void mapping_lane_id_2_lanelet_id(const map_referencepoint& ref_point, const map_lane& lane, const long lane_width, const std::vector<lanelet::ConstLanelet>& subj_lanelets, std::unordered
It is initialized before pass into this function. Please refer to the cpp file to see the usage.

2022-06-09 13:49 UTC, dan-du-car commented on intersection_model/src/intersection_model.cpp
> +        std::unordered_map<long, map_lane> link_departure_lanes_m;
The map object does not state which type of lane. The information from the MAP message will tell you what type of lane it is.

2022-06-09 13:56 UTC, dan-du-car commented on intersection_model/src/intersection_model.cpp
> +        std::vector<signalized_intersection_lanelets> enter_departure_lanelets2SG_id_v;
Each entry and departure combination map to one link lanelet.

2022-06-09 14:02 UTC, paulbourelly999 approved these changes

2022-06-09 14:02 UTC, merged