Feature/snmp client
usdot-fhwa-stol/carma-streets pull request #147
Opened 2022-06-16 16:45 UTC by adev4a

# PR Details
This PR adds the traffic signal controller client. 
## Description
Features developed within this implementation include using the net-snmp library to GET and SET snmp requests.

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
[CARMA Contributing Guide](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) 
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2022-06-17 17:15 UTC, paulbourelly999 commented on tsc_client_service/CMakeLists.txt
> +    test/test_traffic_signal_controller_service
please correct this to only include {TEST_SOURCES}

2022-06-17 17:17 UTC, paulbourelly999 commented on tsc_client_service/CMakeLists.txt
> +src/main.cpp)
Small revision, consistent indentation here.

2022-06-17 17:22 UTC, paulbourelly999 commented on tsc_client_service/include/snmp_client.h
> +#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_TDEBUG
This looks like a type. This should probably be SPDLOG_LEVEL_DEBUG

2022-06-17 17:23 UTC, paulbourelly999 commented on tsc_client_service/include/snmp_client.h
> +#include <rapidjson/document.h>
Please review these include statements I don't think you need them here. They are already included by the streets_service_base header files. Please only include headers, packages you are using. This way we can make sure we are only ever including the things we directly need.

2022-06-17 17:25 UTC, paulbourelly999 commented on tsc_client_service/include/snmp_client.h
> +        // a pointer returned by the library
please use java-doc style comments . For example
```
/**
* @brief <Description>
* @param <Parameter Description>
* @return < Return Description>
*/
```

2022-06-17 17:30 UTC, paulbourelly999 commented on tsc_client_service/include/snmp_client.h
> +        // a pointer returned by the library
Also make sure to include at least a single short sentence to describe any member variable in a java doc comment that is not completely obvious like timestamp or something.

2022-06-17 17:30 UTC, paulbourelly999 commented on tsc_client_service/manifest.json
> +            "description": " ",
Add descriptions for all your configuration parameters please.

2022-06-17 17:34 UTC, adev4a commented on tsc_client_service/include/snmp_client.h
> +        // a pointer returned by the library
This is just additional info from the net-snmp doc, i have those defined for the functions themselves

2022-06-17 18:05 UTC, adev4a commented on tsc_client_service/include/snmp_client.h
> +#define SPDLOG_ACTIVE_LEVEL SPDLOG_LEVEL_TDEBUG
Looks like both of these compile and give debug logs. The documentation however says its SPDLOG_LEVEL_DEBUG @abey-yoseph you'll have to fix this in yours as well

2022-06-20 13:43 UTC, dan-du-car commented on tsc_client_service/include/snmp_client.h
> +         * @param ip The ip ,as a string, for the host to establish snmp communication with.
Which host? The traffic signal controller or the machine running carma-streets?

2022-06-20 13:44 UTC, dan-du-car commented on tsc_client_service/include/snmp_client.h
> +         * @param community The community id as a string. Defaults to "public" if unassigned.
Why do we need community?

2022-06-20 13:47 UTC, dan-du-car commented on tsc_client_service/include/snmp_client.h
> +         *  @return Integer value at the oid, returns -1 if value cannot be requested or oid doesn't have an integer value to return.*/
It is returning Boolean in the method signature.

2022-06-20 14:28 UTC, dan-du-car commented on tsc_client_service/src/snmp_client.cpp
> +        for(auto vars = response->variables; vars; vars = vars->next_variable){
The condition of this loop is vars? Do we need to compare with an end variable?

2022-06-20 14:34 UTC, dan-du-car commented on tsc_client_service/src/snmp_client.cpp
> +    if(!read_objid(input_oid.c_str(), OID, &OID_len)){
Maybe add some inline comments to elaborate this function?

2022-06-20 14:35 UTC, dan-du-car commented on tsc_client_service/src/snmp_client.cpp
> +        snmp_perror(input_oid.c_str());
Maybe add some inline comments to elaborate this function read_objid()?

2022-06-20 14:39 UTC, dan-du-car commented on tsc_client_service/src/snmp_client.cpp
> +            snmp_sess_perror("snmpset", ss);
Why do we need to call this snmp_sess_perror() after we know it is unsuccessful?

2022-06-20 14:41 UTC, dan-du-car commented on tsc_client_service/src/snmp_client.cpp
> +        snmp_free_pdu(response);
Why do we need to free pdu? also the OID_len is only initialized to MAX_OID_LEN, and did not realize it is updated at some point?

2022-06-20 14:56 UTC, adev4a commented on tsc_client_service/include/snmp_client.h
> +         * @param ip The ip ,as a string, for the host to establish snmp communication with.
I guess host here is misleading. It would be the server, which can be the traffic signal controller or any snmp enabled device

2022-06-20 14:56 UTC, adev4a commented on tsc_client_service/CMakeLists.txt
> +link_directories("/usr/lib" "/usr/local/lib")
yes, because the net-snmp lib is getting installed in usr/local

2022-06-20 15:10 UTC, adev4a commented on tsc_client_service/include/snmp_client.h
> +         * @param community The community id as a string. Defaults to "public" if unassigned.
community is like the authentication required for connecting to the tsc. I guess we can think of it like a domain to access for snmp v2 and v1 where there is no password required. 
Its a necessary parameter required for every snmp call and in our case we almost always be "public".

2022-06-20 15:16 UTC, adev4a commented on tsc_client_service/src/main.cpp
> +    std::string input_oid = "1.3.6.1.4.1.1206.4.2.1.1.2.1.21.2";
OID values are specific to each object we are trying to check. This one was just used for testing and will be removed once we have a pub-sub up. 
If we do decide to have an internal dictionary for the OIDs that we want to use, i can add the description there. For now these variables are a temporary hold for any OIDs we want to test.

2022-06-20 15:17 UTC, adev4a commented on tsc_client_service/src/snmp_client.cpp
> +        for(auto vars = response->variables; vars; vars = vars->next_variable){
The condition should end if vars->next_variable doesn't exist

2022-06-20 15:25 UTC, adev4a commented on tsc_client_service/src/snmp_client.cpp
> +                long integer_response = *vars->val.integer;
I think these errors would indicate an issue with net-snmp library itself, because there is a field for variable type which should match the value type. 
If that field is not an integer, we don't parse it within the function. I can still add the check, if you want but that's not how we'd expect it to work.
Same for the value not existing, a variable shouldn't be created for null values.

2022-06-20 15:28 UTC, paulbourelly999 commented on tsc_client_service/CMakeLists.txt
> +    test/test_traffic_signal_controller_service
@adev4a

2022-06-20 15:29 UTC, paulbourelly999 commented on tsc_client_service/include/snmp_client.h
> +        struct snmp_session session;
Why do we have a pointer and regular member variable of the same type. What are these for.

2022-06-20 15:31 UTC, paulbourelly999 commented on tsc_client_service/src/main.cpp
> +    std::string input_oid = "1.3.6.1.4.1.1206.4.2.1.1.2.1.21.2";
If these are just for testing you can probably remove them in your commit. or at least leave inline comments about which portions are just for testing and can be removed.

2022-06-20 15:45 UTC, adev4a commented on tsc_client_service/src/snmp_client.cpp
> +                SPDLOG_INFO("Integer value in object: {0}", integer_response);
Makes sense, i just have it this way right now because we're not using the value. I can pass an integer argument by reference to fill in the value here.

2022-06-20 15:47 UTC, adev4a commented on tsc_client_service/include/snmp_client.h
> +        struct snmp_session session;
The comment above describes this a little, the pointer is set as a pointer to the session. Required for a number of the net-snmp functions. This needs to be a class member because its just been set when initializing the class and then used throughout

2022-06-20 16:29 UTC, dan-du-car commented on tsc_client_service/src/main.cpp
> +    std::string input_oid = "1.3.6.1.4.1.1206.4.2.1.1.2.1.21.2";
Can we use some format like this? and concatenate to a string OID ```
Iso (1) 
.org (3) 
.dod (6) 
.internet (1) 
.private (4)
.transition (868) 
.products (2) 
.chassis (4) 
.card (1)
.slotCps (2)
.cpsSlotSummary (1) 
.cpsModuleTable (1) 
.cpsModuleEntry (1) 
.cpsModuleModel (3) .3562.3
```

2022-06-20 16:30 UTC, dan-du-car commented on tsc_client_service/src/main.cpp
> +    std::string input_oid = "1.3.6.1.4.1.1206.4.2.1.1.2.1.21.2";
I think it should be managed by this particular client if this string is const for every set and get request.

2022-06-20 17:08 UTC, dan-du-car commented on tsc_client_service/manifest.json
> +            "description": " ",
```
Are there any SNMP community string vulnerabilities?
Yes. The fact that the community string is left in plain text is a major security weakness. Furthermore, the frequently used default community string of “public” is the first try that any hacker will make to try to exploit the SNMP system.
```
Refer to: https://www.comparitech.com/net-admin/snmp-community-strings-windows-linux/

2022-06-20 19:53 UTC, adev4a commented on tsc_client_service/manifest.json
> +            "description": " ",
Yes, but this is something that has to be set on the server. So we would need to change it on the traffic signal controller

2022-06-20 20:05 UTC, adev4a commented on tsc_client_service/src/snmp_client.cpp
> +        snmp_free_pdu(response);
We're freeing the response, because its a class member. Once we finish either get/set, we free it so it doesn't corrupt the other methods

2022-06-20 20:07 UTC, adev4a commented on tsc_client_service/src/snmp_client.cpp
> +            snmp_sess_perror("snmpset", ss);
net-snmp generates its own logs. This function is logging the error for the session.

2022-06-20 20:11 UTC, adev4a commented on tsc_client_service/src/main.cpp
> +    std::string input_oid = "1.3.6.1.4.1.1206.4.2.1.1.2.1.21.2";
This string isn't constant for every set and get request. Its an id for each object that we want to get or set. 
I'll remove it from here

2022-06-20 21:27 UTC, dan-du-car commented on tsc_client_service/src/snmp_client.cpp
> +                SPDLOG_INFO("Integer value in object: {0}", integer_response);
Yes, please. You have it.

2022-06-21 00:22 UTC, adev4a commented on tsc_client_service/src/snmp_client.cpp
> +            if(vars->type == ASN_INTEGER){
I looked into this and these are macros, not within a namespace. 
https://github.com/net-snmp/net-snmp/blob/b87296ae3ddd1500eb1c8a08b2769307a335a427/include/net-snmp/library/asn1.h#L68

https://github.com/net-snmp/net-snmp/blob/b87296ae3ddd1500eb1c8a08b2769307a335a427/win32/Snmp-winExtDLL.h#L100

2022-06-21 21:12 UTC, adev4a commented on tsc_client_service/CMakeLists.txt
> +    test/test_traffic_signal_controller_service
Not sure why its not showing up here, if you look at the Cmakelists, this change is on there

2022-06-21 21:14 UTC, paulbourelly999 commented on tsc_client_service/src/snmp_client.cpp
> +                SPDLOG_INFO("Integer value in object: {0}", integer_response);
I agree with @dan-du-car. Also we need to return a value, either by reference as a parameter or from the return statement. Otherwise this is not useable for the next story

2022-06-21 21:36 UTC, paulbourelly999 commented on tsc_client_service/test/test_traffic_signal_controller_service.cpp
> +TEST(traffic_signal_controller_service, test_process_snmp_set_request){
Could we add test cases for invalid oid strings. I think this will increase you test coverage

2022-06-21 21:37 UTC, paulbourelly999 commented on tsc_client_service/test/test_traffic_signal_controller_service.cpp
> +TEST(traffic_signal_controller_service, test_process_snmp_set_request){
Like ones that would make `read_objid` fail/false.

2022-06-21 21:46 UTC, paulbourelly999 requested changes
Once the get method returns values and you fix the cmake test executable target, it is good with me. You could add unit test coverage for invalid oid strings like I suggested pretty easily but it isn't necessary.

2022-06-22 17:26 UTC, paulbourelly999 commented on tsc_client_service/CMakeLists.txt
> +link_directories("/usr/lib" "/usr/local/lib")
You can test this locally but I think these directories are linked by default so this line may not be necessary.

2022-06-22 17:29 UTC, adev4a commented on tsc_client_service/CMakeLists.txt
> +link_directories("/usr/lib" "/usr/local/lib")
Hmm i'm fairly certain /usr/local/libs needs to be added to path to link them

2022-06-23 15:51 UTC, dan-du-car approved these changes

2022-06-24 15:49 UTC, merged

2022-06-28 22:11 UTC, paulbourelly999 commented on tsc_client_service/src/main.cpp
> +    std::string input_oid = "1.3.6.1.4.1.1206.4.2.1.1.2.1.21.2";
I think this is far more complex than the functionality we need for this UC.  What is the benefit of assembling the OID like this. We only have to support like 6-7 OIDs out of allot define in NTCIP. This seems like a lot of extra scope for little benefit.