Readme document the parameters and usage of the signal optimization service current implementation
usdot-fhwa-stol/carma-streets pull request #165
Opened 2022-07-11 15:14 UTC by dan-du-car

# PR Details
Readme document the parameters and usage of the signal optimization service current implementation

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
[CARMA Contributing Guide](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) 
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-07-12 14:11 UTC, dan-du-car commented on signal_opt_service/readme.md
> +This package provides logic for monitoring traffic signal state and planned state, vehicles within the intersection communication area, and the latest intersection geometry. The signal optimization s
https://github.com/usdot-fhwa-stol/carma-streets/pull/165/commits/7ff723a2c97b56f27f8a8795f28654f23fa3dc39

2022-07-12 15:58 UTC, adev4a approved these changes

2022-07-12 16:29 UTC, paulbourelly999 commented on signal_opt_service/readme.md
> +| tsc_spat_msg_in | The topic is used to transfer message between signal optimization and  TSC (Traffic Signal Controller) services. The message is carma-streets internal [spat messages in JSON forma
This topic will be used by more than just the signal optimization. It should be called something more like tsc_spat_msg_out since it is coming from the TSC.

2022-07-12 16:30 UTC, paulbourelly999 commented on signal_opt_service/readme.md
> +### Monitoring
To be inline with out other documentation could we call this Introduction

2022-07-12 16:33 UTC, paulbourelly999 commented on signal_opt_service/readme.md
> +* The SO service depends on message service, intersection model and TSC (Traffic Signal Controller) service. It subscribes to message service to get the vehicle status and intent information, calls t
We should probably include a confluence link to the signal optimization algorithm confluence page on here as well.

2022-07-12 16:44 UTC, dan-du-car commented on signal_opt_service/readme.md
> +### Monitoring
I would prefer to have more specific description than introduction.

2022-07-12 16:45 UTC, dan-du-car commented on signal_opt_service/readme.md
> +| tsc_spat_msg_in | The topic is used to transfer message between signal optimization and  TSC (Traffic Signal Controller) services. The message is carma-streets internal [spat messages in JSON forma
Yeah, for the optimization service, it is coming in from tsc service, not out. The naming in this context seems fine to me.

2022-07-12 18:27 UTC, paulbourelly999 commented on signal_opt_service/readme.md
> +### Monitoring
Change this to introduction

2022-07-12 18:28 UTC, paulbourelly999 commented on signal_opt_service/readme.md
> +* The SO (Signal Optimization) service is the CARMA-Streets service responsible for optimizing traffic signal controller phase order and duration. The SO service is responsible for fixing a configura
Remove bullet point

2022-07-12 18:49 UTC, paulbourelly999 commented on signal_opt_service/readme.md
> +| int_client_request_attempts | The maximum numbers of loop to send HTTP request to intersection model to get the latest intersection geometry information.|
**New Section**
## Implementation
The SO service consist of two main classes. The first is the `signal_opt_messages_worker`. This is a worker class the holds the pointers to all the persisted data. This includes the **intersection_info** (intersection geometry), **spat** (traffic signal current and future state information) and the **vehicle_list** (vehicle currently in the intersection). This worker class contains methods to update this persisted data and the get shared pointers to it. The second class is the `signal_opt_service'. This class initializes and instance of the `signal_opt_message_worker', reads in configuration parameters from the **manifest.json** and creates threads for kafka consumers for the **status_and_intent** and **spat** messages. These kafka consumers will call the `signal_opt_messages_worker` methods to update the stored persistence objects :  **vehicle_list** and **spat**.

2022-07-13 15:01 UTC, paulbourelly999 requested changes
I left some comments about changes to make. Please review and let me know what you think

2022-07-13 15:50 UTC, dan-du-car commented on signal_opt_service/readme.md
> +### Monitoring
https://github.com/usdot-fhwa-stol/carma-streets/pull/165/commits/2fa526697d96479085be08b94df43fa5d17da6c2

2022-07-13 15:51 UTC, dan-du-car commented on signal_opt_service/readme.md
> +| int_client_request_attempts | The maximum numbers of loop to send HTTP request to intersection model to get the latest intersection geometry information.|
https://github.com/usdot-fhwa-stol/carma-streets/pull/165/commits/2fa526697d96479085be08b94df43fa5d17da6c2

2022-07-13 15:58 UTC, dan-du-car commented on signal_opt_service/readme.md
> +This worker class contains methods to update this persisted data and the get shared pointers to it. The second class is the `signal_opt_service'. This class initializes and instance of the `signal_op
https://github.com/usdot-fhwa-stol/carma-streets/pull/165/commits/a16b524525e69f85603b224dbda74ff79a7a4af5

2022-07-13 15:59 UTC, paulbourelly999 approved these changes

2022-07-13 15:59 UTC, merged