Feature/monitor tsc state
usdot-fhwa-stol/carma-streets pull request #168
Opened 2022-07-25 02:12 UTC by adev4a

# PR Details
This PR adds functionality to the  tsc_service to monitor the traffic signal controller(TSC) state. The state is defined as a collection of configurations which are requested from the TSC through SNMP get calls.

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?
Unit Tested and Integration tested.

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
[CARMA Contributing Guide](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) 
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2022-07-26 13:30 UTC, paulbourelly999 commented on tsc_client_service/CMakeLists.txt
> +target_link_libraries(${PROJECT_NAME}_test
is there a cleaner way to do this? From the googletest README.md it looks like you should be able to just call
```
find_package(GTest::gtest)
find_package(GTest::gmock)

target_link_libraries(${PROJECT_NAME}_test PUBLIC GTest::gtest GTest::gmock)
or 
target_link_libraries(${PROJECT_NAME}_test PUBLIC gtest gmock)

```

2022-07-26 13:31 UTC, paulbourelly999 commented on tsc_client_service/include/monitor_tsc_state.h
> +        int signal_group_id;
Leave comment about how `signal_group_id` is J2735 identifier and `phase_num` is NTCIP identifier

2022-07-26 13:39 UTC, paulbourelly999 commented on tsc_client_service/include/monitor_tsc_state.h
> +    struct signal_group_state
For classes/structs like this we should start leaving javadoc comments about what these are meant to be used for and how they are used.

2022-07-26 13:41 UTC, paulbourelly999 commented on tsc_client_service/include/monitor_tsc_state.h
> +        int red_duration;
Since this is not a NTCIP defined property, we should probably make sure we explicitly define what this measurement is. In our case it is the total time a phase is predicted to be red before its next green transition right?

2022-07-26 13:41 UTC, paulbourelly999 commented on tsc_client_service/include/monitor_tsc_state.h
> +        int min_green;
None of these have units. I assume they are milliseconds right.

2022-07-26 13:42 UTC, paulbourelly999 commented on tsc_client_service/include/monitor_tsc_state.h
> +        std::vector<int> phase_seq_ring1_;
once we add pedestrian phases we may want to ensure that it is clear we are assuming the first two rings are vehicle phases only.

2022-07-26 13:44 UTC, paulbourelly999 commented on tsc_client_service/include/snmp_client.h
> +        STRING
How is phase sequence returned. Is it `STRING` response type?

2022-07-26 13:47 UTC, paulbourelly999 commented on tsc_client_service/src/monitor_tsc_state.cpp
> +        std::string phase_seq_oid= ntcip_oids::SEQUENCE_DATA + "." + "1" + "." + std::to_string(ring_num); //Sequence 1 for ring
why is the additional `.1.` not part of the constant?

2022-07-26 13:50 UTC, paulbourelly999 commented on tsc_client_service/src/snmp_client.cpp
> +                        SPDLOG_INFO("Integer value in object: {0}", val.val_int);
Does this log statement need to be info level.

2022-07-26 13:53 UTC, paulbourelly999 requested changes
Left some comments about documentation mostly. Everything looks good to me. The only change I am passionate about is the CMakeList.txt file changes. Seems like a weird way to include a pretty standard library. Please check if we can use find_package instead

2022-07-26 17:52 UTC, adev4a commented on tsc_client_service/include/snmp_client.h
> +        STRING
Yes, Sequence and concurrent phases are returned as string responses

2022-07-26 17:53 UTC, adev4a commented on tsc_client_service/src/monitor_tsc_state.cpp
> +        std::string phase_seq_oid= ntcip_oids::SEQUENCE_DATA + "." + "1" + "." + std::to_string(ring_num); //Sequence 1 for ring
The .1. defines the sequence number and the next constant defines the ring. Since we are only querying sequence 1 by default, that's hard coded here

2022-07-27 03:49 UTC, paulbourelly999 approved these changes
Looks good to me

2022-07-28 02:28 UTC, dan-du-car commented on tsc_client_service/include/monitor_tsc_state.h
> +        /*Default Green duration for phase in miiliseconds*/
milliseconds

2022-07-28 02:31 UTC, dan-du-car commented on tsc_client_service/src/monitor_tsc_state.cpp
> +        for (const auto& phase : signal_group_phase_map_)
Can we remove this for loops just for print purpose?

2022-07-28 02:41 UTC, dan-du-car commented on tsc_client_service/src/snmp_client.cpp
> +            if(val.type == snmp_response_obj::response_type::INTEGER){
Why do we have two different response types, and it seems to only print the data after the conditional checking.

2022-07-28 14:02 UTC, adev4a commented on tsc_client_service/src/monitor_tsc_state.cpp
> +        for (const auto& phase : signal_group_phase_map_)
I've added this intentionally so we can see the mapped values. I think it would be useful to keep in the log, but if you think its not, i can remove it

2022-07-28 14:04 UTC, adev4a commented on tsc_client_service/src/snmp_client.cpp
> +            if(val.type == snmp_response_obj::response_type::INTEGER){
We have 2 different types of values that we are requesting, integer and string. This represents that. 
Since the request method is common for both of them, specifying the type lets us know which response type to process

2022-07-29 01:15 UTC, merged