add following events
usdot-fhwa-stol/carma-streets pull request #181
Opened 2022-08-11 16:46 UTC by adev4a

# PR Details
This PR adds methods to update incoming spat with future movement events for each signal group in the spat msg.
## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
[CARMA Contributing Guide](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) 
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2022-08-15 13:15 UTC, paulbourelly999 commented on tsc_client_service/include/monitor_tsc_state.h
> +            FRIEND_TEST(traffic_signal_controller_service, test_get_following_movement_events);
Could you link some documentation to how you came up with this implementation to help me understand it.

2022-08-15 13:20 UTC, paulbourelly999 commented on tsc_client_service/src/monitor_tsc_state.cpp
> +                    SPDLOG_ERROR("This movement phase is not supported. Movement phase type: {0}", int(current_movement.state_time_speed.front().event_state));
Please confirm this but I believe unused phases will be movement_phase_state::dark and pedestrian phases will be walk clear or don't walk so this is probably not an exit condition. Maybe a debug log will help us see when this condition is meant. Similar stuff can be said for the switch statement above.

2022-08-15 13:23 UTC, paulbourelly999 commented on tsc_client_service/src/monitor_tsc_state.cpp
> +                throw snmp_client_exception("Event list has more than one events, not usable when adding future movement events. Associated with Signal Group:" + std::to_string(signal_group_id));
Lets use a  different exception for this, since it really does not have anything to do with SNMP client.

2022-08-15 13:24 UTC, paulbourelly999 commented on tsc_client_service/src/monitor_tsc_state.cpp
> +                    return false; //TODO: Should this be an exit condition?
Since this is the only condition that will cause this method to return false maybe we should switch this to a void method and catch any exception it throughs.

2022-08-15 13:25 UTC, adev4a commented on tsc_client_service/include/monitor_tsc_state.h
> +            FRIEND_TEST(traffic_signal_controller_service, test_get_following_movement_events);
Yes, sure. Here's some documentation describing it https://google.github.io/googletest/reference/testing.html#FRIEND_TEST

2022-08-15 15:54 UTC, adev4a commented on tsc_client_service/src/monitor_tsc_state.cpp
> +                    SPDLOG_ERROR("This movement phase is not supported. Movement phase type: {0}", int(current_movement.state_time_speed.front().event_state));
So, phases that are not vehicle phases would never be evaluated at this point, because on Line 141 we ignore phases not in the state_map.
These would however include vehicle phases like dark, permissive_movement_allowed etc.I can change this to a debug log, but we also need to add an exception here, since it would fail Line 167 and 168

2022-08-16 15:55 UTC, paulbourelly999 commented on tsc_client_service/include/tsc_service.h
> +            bool use_tsc_state_spat_update_ = true;
We probably want to read this parameter from the manifest json using the streets_configuration singleton like we do for the other configuration parameter instead of hard coding it.

2022-08-16 15:56 UTC, paulbourelly999 requested changes
Use streets_configuration to read configuration from manifest json

2022-08-16 18:15 UTC, Saeid-Solei commented on tsc_client_service/include/monitor_tsc_state.h
> +            int required_following_movements_ = 3;
Could you explain what is this parameter? is this the configurable number of future phases in the modified spat?

2022-08-16 18:35 UTC, paulbourelly999 commented on tsc_client_service/include/monitor_tsc_state.h
> +            int required_following_movements_ = 3;
Yes we could add it but we probably don't need to add it as a parameter read from the manifest json

2022-08-16 18:36 UTC, paulbourelly999 commented on tsc_client_service/src/tsc_service.cpp
> +            bool use_tsc_state_spat_update_ = streets_service::streets_configuration::get_boolean_config("use_tsc_state_spat_update");
This is incorrect. Why do you have a class member and a local variable. Remove the local variable and just set the class member

2022-08-16 20:56 UTC, paulbourelly999 approved these changes
Looks good to me!

2022-08-16 22:02 UTC, dan-du-car approved these changes

2022-08-16 22:02 UTC, merged