Intersection Model: Add generated server code and update intersection library
usdot-fhwa-stol/carma-streets pull request #19
Opened 2021-10-14 21:53 UTC by dan-du-car

# PR Details
## Description
Add generated server code and update intersection library.

## Related Issue
https://github.com/usdot-fhwa-stol/carma-streets/issues/12

## Motivation and Context

## How Has This Been Tested?
Local integration testing
Unit tests

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
[CARMA Contributing Guide](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) 
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-10-19 12:29 UTC, paulbourelly999 commented on intersection_model/readme.md
> +apt-get update  && apt-get install -y cmake libboost1.65-all-dev git autotools-dev automake sqlite3 libsqlite3-dev curl libpugixml-dev libgeographic-dev qtbase5-dev qtbase5-dev-tools libqhttpengine-d
missing libssl-dev

2021-10-19 12:31 UTC, paulbourelly999 commented on docker-compose.yml
> +  intersection_model:
Why do we have an image for the intersection_model. This is just suppose to be a library that the message service uses

2021-10-19 12:34 UTC, paulbourelly999 commented on intersection_model/Dockerfile
> -ENTRYPOINT [ "/home/carma-streets/intersection_model/entrypoint.sh" ]
In order to run the intersection_model executable in a shell that has the ros medolic setup.bash sourced and the lanelet2 install setup.bash sourced this line was necessary. Why is it no longer necessary? Have you tried running the docker image to see if it can still find the lanelet2 depedencies

2021-10-19 12:41 UTC, paulbourelly999 commented on intersection_model/include/intersection_model.h
> +            std::vector<int> get_shared_entry_link_lanelet_ids(int64_t subject_link_lanelet_id);
Not sure I understand what this method is for

2021-10-19 12:45 UTC, paulbourelly999 commented on intersection_model/intersection_model_v1.yaml
> +          description: Unexpected error
I think the correct way to reflect errors would be with http status code like :
`responses:
        '201':
            description: Created   
        '400':
            description: Bad Request  `

2021-10-19 12:48 UTC, paulbourelly999 commented on intersection_model/src/server/Dockerfile
> +ENTRYPOINT ["/usr/server/build/src/cpp-qt-qhttpengine-server"]
Why does the REST server have a separate Dockerfile. It shouldn't be a separate service right?

2021-10-19 12:50 UTC, paulbourelly999 commented on intersection_model/src/server/Makefile
> +BUILD_DIR=build
Should this be committed??

2021-10-19 12:52 UTC, paulbourelly999 commented on intersection_model/src/server/external/lib/cmake/qhttpengine/qhttpengineConfig.cmake
> +
This should no be committed

2021-10-19 12:52 UTC, paulbourelly999 commented on intersection_model/src/server/external/lib/cmake/qhttpengine/qhttpengineConfig-noconfig.cmake
> +#----------------------------------------------------------------
This should not be committed

2021-10-19 12:52 UTC, paulbourelly999 commented on intersection_model/src/server/external/lib/cmake/qhttpengine/qhttpengineConfigVersion.cmake
> +# This is a basic version file for the Config-mode of find_package().
This should not be committed

2021-10-19 12:53 UTC, paulbourelly999 commented on intersection_model/src/server/external/lib/libqhttpengine.so
> +libqhttpengine.so.1
This should not be committed right ?

2021-10-19 12:53 UTC, paulbourelly999 commented on intersection_model/src/server/external/lib/libqhttpengine.so.1
> +libqhttpengine.so.1.0.1
This should not be committed right

2021-10-19 12:58 UTC, paulbourelly999 commented on intersection_model/test/test_intersection_model.cpp
> +    lanelet::Lanelet lane = model->get_lanelet(38.9551104, -77.1498214);
I was having trouble getting this method to return the correct lanelet when using a point inside the lanelet. I would often get the adjacent lanelet. Did you change the logic for the get_lanelet at all.

2021-10-19 13:46 UTC, dan-du-car commented on docker-compose.yml
> +  intersection_model:
It is itself also a REST service.

2021-10-19 13:47 UTC, dan-du-car commented on intersection_model/Dockerfile
> -ENTRYPOINT [ "/home/carma-streets/intersection_model/entrypoint.sh" ]
Line 128 has already sourced the setup.bash.

2021-10-19 13:49 UTC, dan-du-car commented on intersection_model/include/intersection_model.h
> +            std::vector<int> get_shared_entry_link_lanelet_ids(int64_t subject_link_lanelet_id);
It gets the list of link lanelets that vehicles enter from the same entry lane.

2021-10-19 13:54 UTC, dan-du-car commented on intersection_model/readme.md
> +apt-get update  && apt-get install -y cmake libboost1.65-all-dev git autotools-dev automake sqlite3 libsqlite3-dev curl libpugixml-dev libgeographic-dev qtbase5-dev qtbase5-dev-tools libqhttpengine-d
Addressed

2021-10-19 19:50 UTC, dan-du-car commented on intersection_model/src/server/external/lib/cmake/qhttpengine/qhttpengineConfigVersion.cmake
> +# This is a basic version file for the Config-mode of find_package().
removed

2021-10-20 00:08 UTC, paulbourelly999 requested changes

2021-10-20 00:31 UTC, dan-du-car commented on intersection_model/Dockerfile
> -ENTRYPOINT [ "/home/carma-streets/intersection_model/entrypoint.sh" ]
yes, I can build docker image and run as container without this ENTRYPOINT line.

2021-10-20 00:36 UTC, dan-du-car commented on intersection_model/src/server/src/handlers/OAIApiRouter.h
> +            //     emit requestReceived(socket);
It generated errors. Yeah, it is generated code, and I had to comment out to get it to work.

2021-10-20 01:01 UTC, paulbourelly999 commented on intersection_model/Dockerfile
> -ENTRYPOINT [ "/home/carma-streets/intersection_model/entrypoint.sh" ]
So if you tell me it works without that is fine, but I know for a fact that dockerfiles can have both entrypoint and CMD at the same time. CARMA-Platform has entrypoint in its base images and them CMD in its image. Also I tested this dockerfile and it did build. But if you say the docker image runs without it then that is fine to. We probably want to remove the scripts then if it runs without this. My experience was that the docker image would fail to run if we did not have this line and the entrypoint.sh and init-env.sh scripts.

2021-10-20 01:04 UTC, paulbourelly999 commented on intersection_model/Dockerfile
> -ENTRYPOINT [ "/home/carma-streets/intersection_model/entrypoint.sh" ]
If it builds and runs without we need to remove the entrypoint and init-env.sh scripts since they are no longer necessary.

2021-10-20 12:03 UTC, merged