Broadcast tsc config
usdot-fhwa-stol/carma-streets pull request #192
Opened 2022-08-29 16:32 UTC by adev4a

# PR Details
## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
[CARMA Contributing Guide](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) 
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-09-06 12:48 UTC, paulbourelly999 commented on streets_utils/streets_tsc_configuration/CMakeLists.txt
> +                Boost::system
If you include the library you do not need to include its dependencies. Those will automatically be included I think.

2022-09-06 12:50 UTC, paulbourelly999 commented on streets_utils/streets_tsc_configuration/README.md
> +Traffic signal controller configuration represents the setup on the physical device. In order to access that information SNMP requests need to be sent to the system. In order to control the current p
When writing a paragraph in MD you do not need to add new line characters. The viewer will line wrap appropriately.

2022-09-06 12:52 UTC, paulbourelly999 commented on tsc_client_service/include/tsc_service.h
> +            bool use_tsc_state_spat_update_ = true;
Why did you add this parameter back. We only need a single parameter for using spat or desired phase plan

2022-09-06 12:54 UTC, paulbourelly999 commented on tsc_client_service/src/tsc_service.cpp
> +                std::this_thread::sleep_for(std::chrono::milliseconds(100)); // Sleep for 5 seconds between publish
This will only sleep for .1 seconds right? (100 ms = 0.1 seconds)

2022-09-06 13:11 UTC, paulbourelly999 requested changes
Left some comments

2022-09-06 14:00 UTC, adev4a commented on tsc_client_service/src/tsc_service.cpp
> +                std::this_thread::sleep_for(std::chrono::milliseconds(100)); // Sleep for 5 seconds between publish
Yes, I had to change this because some of the other unit tests were timing out with a 5 second sleep. I can update the comment

2022-09-06 14:01 UTC, adev4a commented on tsc_client_service/include/tsc_service.h
> +            bool use_tsc_state_spat_update_ = true;
Must have come through with a bad merge with develop, I'll remove it

2022-09-06 14:48 UTC, adev4a commented on streets_utils/streets_tsc_configuration/CMakeLists.txt
> +                Boost::system
Not sure i understand which dependencies you're talking about here

2022-09-07 13:29 UTC, paulbourelly999 commented on streets_utils/streets_tsc_configuration/README.md
> +as well as the duration of yellow and red clearance, which cannot be controlled directly.The tsc_config_state message consists of this information for all **active vehicle phases/signal_groups**.
This does not need an end line character

2022-09-07 14:22 UTC, Saeid-Solei commented on streets_utils/streets_tsc_configuration/src/tsc_configuration_state.cpp
> +        }
Would it be better if we always have the member, but leave it empty if the signal group does not have concurrent signal groups?

2022-09-07 14:28 UTC, Saeid-Solei commented on streets_utils/streets_tsc_configuration/test/test_tsc_configuration_state.cpp
> +    ASSERT_FALSE(config_json.empty());
I do not see any test related to concurrent_signal_groups. Since the data type of the concurrent_signal_groups is different than others, could you add an Assert statement for the concurrent_signal_groups?

2022-09-07 17:48 UTC, adev4a commented on streets_utils/streets_tsc_configuration/src/tsc_configuration_state.cpp
> +        }
I would be ok with that, but i wasn't sure how the Get Int call would work in cases where the list is empty. I couldn't find a method to check size of the array before reading. 
Either way this is just for conversion to and from Json. For any service using the message it would effectively be the same, since the state struct still has a concurrent_signal_groups member, which would be empty.

2022-09-07 17:50 UTC, paulbourelly999 commented on streets_utils/streets_tsc_configuration/src/tsc_configuration_state.cpp
> +        }
@adev4a  Either way works but please make sure you document in the readme how this will be treated if there are no concurrent groups, preferably as a comment to the JSON payload and also in a paragraph somewhere. Currently it looks like we are treating `concurrent_signal_groups` as a optional field which is fine. Please leave a comment that when it is empty the field will be missing. Good catch @Saeid-Solei

2022-09-07 17:51 UTC, paulbourelly999 requested changes
Please update documentation to describe how you expect phases with no concurrent signal groups to be sent.

2022-09-07 19:41 UTC, Saeid-Solei approved these changes

2022-09-07 22:02 UTC, paulbourelly999 approved these changes

2022-09-07 22:02 UTC, merged