195 scheduling mapping issue
usdot-fhwa-stol/carma-streets pull request #203
Opened 2022-09-01 19:19 UTC by Saeid-Solei

# PR Details
## Description

Currently, the signalized_vehicle_scheduler assumes that each entry lane from the intersection_model is connected to a given signal group id and has a signal group id field. But actually, each connection link inside the intersection box have a signal group id field rather than each entry lane.

In signalized_vehicle_scheduler, there is a method that provides the movement_state list for each entry lane based on the entry lane id and its associated signal group ids. This method needs to be updated to provide the movement_state list for each vehicle\entry lane based on the connection lane ids and their associated signal group ids.

## Related Issue

https://github.com/usdot-fhwa-stol/carma-streets/issues/195

## Motivation and Context

## How Has This Been Tested?
Unit Tests

## Types of changes

- [x] Defect fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
[CARMA Contributing Guide](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) 
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2022-09-06 12:41 UTC, paulbourelly999 commented on streets_utils/streets_vehicle_scheduler/src/signalized_vehicle_scheduler.cpp
> +                    throw scheduling_exception("The link lanelet does not have group_id!");
Please make these exceptions clearer since they do not indicate and an illegal MAP. They just violate one of our simplifying assumptions. Please state the simplifying assumption. So something more like:

This entry lanes has not connection lanes 
or 
This entry lane has multiple connection lanes with different signal group ids. The signalized vehicle scheduler is only capable of understanding intersection where all connection lanes from a single entry lane share a signal group id.

2022-09-06 12:42 UTC, paulbourelly999 commented on streets_utils/streets_vehicle_scheduler/src/signalized_vehicle_scheduler.cpp
>      signal_phase_and_timing::movement_state signalized_vehicle_scheduler::find_movement_state_for_lane(const OpenAPI::OAILanelet_info &entry_lane_info) const {
Update the documentation for this method

2022-09-06 12:44 UTC, paulbourelly999 commented on streets_utils/streets_vehicle_scheduler/src/signalized_vehicle_scheduler.cpp
> +            if ( std::count(connection_lanelet_ids.begin(), connection_lanelet_ids.end(), lane.getId()) ) {
What is this if statement meant to do. Has this been locally tested against a MAP?

2022-09-06 12:46 UTC, paulbourelly999 commented on streets_utils/streets_vehicle_scheduler/src/signalized_vehicle_scheduler.cpp
> +        for ( const auto &lane : intersection_info->getLinkLanelets() ) {
Why are we looping through all connection lanes?

2022-09-07 13:33 UTC, Saeid-Solei commented on streets_utils/streets_vehicle_scheduler/src/signalized_vehicle_scheduler.cpp
> +                    throw scheduling_exception("The link lanelet does not have group_id!");
The first throw happens when a link lanelet does not have a group id. This is a MAP error I believe.
The second throw happens when the UC3 assumption (the assumption of all link lanelets from a signle entry lane share a signal_group_id) is not satisfied. I have added another sentence to explain this as you suggested.

2022-09-07 13:33 UTC, Saeid-Solei commented on streets_utils/streets_vehicle_scheduler/src/signalized_vehicle_scheduler.cpp
>      signal_phase_and_timing::movement_state signalized_vehicle_scheduler::find_movement_state_for_lane(const OpenAPI::OAILanelet_info &entry_lane_info) const {
Done!

2022-09-07 13:34 UTC, Saeid-Solei commented on streets_utils/streets_vehicle_scheduler/src/signalized_vehicle_scheduler.cpp
> +            if ( std::count(connection_lanelet_ids.begin(), connection_lanelet_ids.end(), lane.getId()) ) {
If the connection link "lane" is included in the list of connection links that are connected to the entry lane.
And yes, no unit test fails.

2022-09-07 17:53 UTC, paulbourelly999 commented on streets_utils/streets_vehicle_scheduler/src/signalized_vehicle_scheduler.cpp
> +            if ( std::count(connection_lanelet_ids.begin(), connection_lanelet_ids.end(), lane.getId()) ) {
Leave a comment to describe that you are confirming the lane id exists in the vector of connection_lanelet_ids

2022-09-07 17:54 UTC, paulbourelly999 commented on streets_utils/streets_vehicle_scheduler/include/signalized_vehicle_scheduler.h
> +             * at the intersection box shall be able to receive protected green at the same time.
We haven't been great at documenting this but add a @throws descriptions of when this method will throw and exception.

2022-09-07 17:55 UTC, paulbourelly999 requested changes
Make the suggested changes

2022-09-08 00:56 UTC, adev4a commented on streets_utils/streets_vehicle_scheduler/src/signalized_vehicle_scheduler.cpp
> +            if ( std::count(connection_lanelet_ids.begin(), connection_lanelet_ids.end(), lane.getId()) ) {
If we just want to check if that specific Id exists in the list, why not just use std::find? count is trying to get the number of occurrences, so it will go through the complete list before stopping, std::find will stop as soon as the element is found.

2022-09-08 00:56 UTC, adev4a commented on streets_utils/streets_vehicle_scheduler/src/signalized_vehicle_scheduler.cpp
> +            auto connection_lanelet_ids = entry_lane_info.getConnectingLaneletIds();
connection_lanelet_ids remains unchanged in the for loop, it should be created outside of it

2022-09-08 00:56 UTC, adev4a commented on streets_utils/streets_vehicle_scheduler/src/signalized_vehicle_scheduler.cpp
>          return move_state;
Looks like if we reach here, move_state is unassigned, should we be returning an uninitialized variable? Or throw an exception that movement_state with the required signal_group_id wasn't found

2022-09-08 17:22 UTC, Saeid-Solei commented on streets_utils/streets_vehicle_scheduler/src/signalized_vehicle_scheduler.cpp
> +            if ( std::count(connection_lanelet_ids.begin(), connection_lanelet_ids.end(), lane.getId()) ) {
Good point. Done!

2022-09-08 17:22 UTC, Saeid-Solei commented on streets_utils/streets_vehicle_scheduler/src/signalized_vehicle_scheduler.cpp
> +            auto connection_lanelet_ids = entry_lane_info.getConnectingLaneletIds();
Corrected.

2022-09-08 17:22 UTC, Saeid-Solei commented on streets_utils/streets_vehicle_scheduler/src/signalized_vehicle_scheduler.cpp
>          return move_state;
You are right. One throw is missing and I have added it. 
I think it will not reach to this last return. But I kept it here to get rid of the code smell. Essentially, this function with either return a valid move_state or throw an exception.

2022-09-08 17:22 UTC, Saeid-Solei commented on streets_utils/streets_vehicle_scheduler/include/signalized_vehicle_scheduler.h
> +             * at the intersection box shall be able to receive protected green at the same time.
Done!

2022-09-08 17:22 UTC, Saeid-Solei commented on streets_utils/streets_vehicle_scheduler/src/signalized_vehicle_scheduler.cpp
> +            if ( std::count(connection_lanelet_ids.begin(), connection_lanelet_ids.end(), lane.getId()) ) {
Done!

2022-09-08 17:27 UTC, adev4a commented on streets_utils/streets_vehicle_scheduler/src/signalized_vehicle_scheduler.cpp
>          return move_state;
In that case a better way to handle the code smell is removing the return from the loop and replacing it with a break. That way your final return is valid

2022-09-08 18:10 UTC, adev4a approved these changes

2022-09-08 19:12 UTC, merged