Issue-247: Add streets_signal_optimization to signal_opt_service
usdot-fhwa-stol/carma-streets pull request #248
Opened 2022-11-01 12:16 UTC by Saeid-Solei

# PR Details
## Description

The streets_signal_optimization library contains the logic for calculating the queue length and dissipation time for each entry lane, find the list of candidate desired phase plans, and pick the one that has the highest delay ratio. This story is created to add the streets_signal_optimization library to signal_opt_service.

## Related Issue

## Motivation and Context

https://github.com/usdot-fhwa-stol/carma-streets/issues/247

## How Has This Been Tested?

Yes, with Unit Tests.

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
[CARMA Contributing Guide](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) 
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2022-11-07 13:39 UTC, paulbourelly999 commented on signal_opt_service/CMakeLists.txt
> +    streets_service_base_lib::streets_service_base_lib
I think you can remove all the stuff after :: we found out. Just so its consistent

2022-11-07 13:42 UTC, paulbourelly999 commented on signal_opt_service/include/signal_opt_processing_worker.h
> +         * @brief Configure streets_signal_optimization library.
**Non critical**: Comment and method name do not make sense together. Either configures signal_opt_processing_worker or configures arbitrator and generator  or rename work to dpp optimizer.

2022-11-07 13:46 UTC, paulbourelly999 commented on signal_opt_service/manifest.json
> +            "name": "dpp_producer_sleep_time",
So can we name/describe this configuration parameter a little better. I assume we only have one frequency for signal optimization now. So this is the time between checking if the spat has  <= configured max fixed phases right.

2022-11-07 13:47 UTC, paulbourelly999 commented on signal_opt_service/manifest.json
> +            "value": 2000,
Is 2 second default reasonable. Lets start with this at 0 and then with performance tune it up to try and improve behavior.

2022-11-07 13:49 UTC, paulbourelly999 commented on signal_opt_service/manifest.json
> +            "value": 3000,
Is 3 seconds reasonable here. Also will this impact our testing at all without queuing. If it won't impact our testing maybe we keep it at 0 to indicate/ensure it does not impact anything unintended.

2022-11-07 13:50 UTC, paulbourelly999 commented on signal_opt_service/manifest.json
> +            "value": 5000,
Ok so we don't use the values from tsc config?

2022-11-07 13:51 UTC, paulbourelly999 commented on signal_opt_service/src/signal_opt_service.cpp
> +        SPDLOG_INFO("Starting desired phase plan producer thread.");
Not a useful log statement.

2022-11-07 13:56 UTC, paulbourelly999 commented on streets_utils/streets_signal_optimization/src/streets_desired_phase_plan_arbitrator.cpp
> +                    logger->info( "\n" );
Why are we logging new lines here. Also this will log 2 new lines. Is that intentional.

2022-11-07 13:58 UTC, paulbourelly999 commented on streets_utils/streets_signal_optimization/src/streets_desired_phase_plan_arbitrator.cpp
> +        std::string so_info = "";
This is not csv. Or atleast not the way we have been using CSV. There is no need to write the field names for each entry. The optimal way to do this would be to write the first line of headers in the configure method and then just log values for every new line.

2022-11-07 14:01 UTC, paulbourelly999 commented on streets_utils/streets_signal_optimization/src/streets_desired_phase_plan_arbitrator.cpp
> +        so_info += "\n";
A call to SPDLOG_INFO(payload) will already append an \n. If you include a additional one each log statement will be separated by a new line.

2022-11-07 14:02 UTC, paulbourelly999 commented on streets_utils/streets_signal_optimization/test/test_streets_desired_phase_plan_arbitrator.cpp
> +                SPDLOG_ERROR("vehicle update is not array!");
DO NOT DO THIS! Either log and error or throw and exception. What ever calls this method or its parent will have to catch the exception and then chose to log something or do something or both but throwing an exception and logging the same thing is a log is a little redundant.

2022-11-07 14:11 UTC, paulbourelly999 commented on kafka_clients/include/kafka_producer_worker.h
> +            virtual bool is_running() const;
Is this a method you added? Why is this method necessary?

2022-11-07 14:12 UTC, dan-du-car commented on kafka_clients/include/kafka_producer_worker.h
> +             */
Is this part of your changes?

2022-11-07 14:32 UTC, dan-du-car commented on streets_utils/streets_signal_optimization/include/streets_desired_phase_plan_generator.h
> +             * signal groups included in the movement groups list are included in the intersection_info pointer. Basically,
Why movement group might not be in the intersection model?

2022-11-07 14:34 UTC, dan-du-car commented on streets_utils/streets_signal_optimization/src/streets_desired_phase_plan_arbitrator.cpp
> +                float delay_measure = calculate_delay_measure(schedule_ptr, candidate_dpp, enable_so_logging);
Why do we need to enable logging for this lib? but not other libs?

2022-11-07 14:47 UTC, Saeid-Solei commented on signal_opt_service/manifest.json
> +            "name": "dpp_producer_sleep_time",
Do you have any name in mind?

2022-11-07 15:05 UTC, Saeid-Solei commented on signal_opt_service/manifest.json
> +            "value": 5000,
Tsc_config does not have min_green member!

2022-11-07 15:12 UTC, Saeid-Solei commented on streets_utils/streets_signal_optimization/src/streets_desired_phase_plan_arbitrator.cpp
> +                    logger->info( "\n" );
Yes, I wanted to create one empty line gap between two consecutive iterations of the SO service. And why  two new lines?

2022-11-07 15:19 UTC, Saeid-Solei commented on kafka_clients/include/kafka_producer_worker.h
> +             */
yes

2022-11-07 15:20 UTC, Saeid-Solei commented on signal_opt_service/src/signal_opt_service.cpp
> +            streets_desired_phase_plan::streets_desired_phase_plan spat_dpp = _so_processing_worker_ptr->convert_spat_to_dpp(_spat_ptr, _movement_groups_ptr);
I believe it should be the latest spat.

2022-11-07 15:22 UTC, Saeid-Solei commented on streets_utils/streets_signal_optimization/include/streets_desired_phase_plan_generator.h
> +             * signal groups included in the movement groups list are included in the intersection_info pointer. Basically,
Basically, the list of movement groups could include a signal group that is not defined in the map\intersection_info. There is no check to protect against this anywhere else. And the dpp_generator requires all signal groups used in movement group list be defined in intersection_info.

2022-11-07 15:23 UTC, Saeid-Solei commented on streets_utils/streets_signal_optimization/src/streets_desired_phase_plan_arbitrator.cpp
> +                for (const auto& veh_sched : all_schedule_ptr->vehicle_schedules) {
I have added a comment to say why this new piece is added (Line 45: // Add those vehicles that are within SO radius to schedule_ptr)

2022-11-07 15:27 UTC, Saeid-Solei commented on signal_opt_service/CMakeLists.txt
> +    streets_service_base_lib::streets_service_base_lib
Done

2022-11-07 15:27 UTC, Saeid-Solei commented on signal_opt_service/include/signal_opt_processing_worker.h
> +         * @brief Configure streets_signal_optimization library.
Done

2022-11-08 13:09 UTC, paulbourelly999 commented on signal_opt_service/CMakeLists.txt
> +    streets_service_base_lib::streets_service_base_lib
It should be, there is a different issue if you run into a compilation issue here. All the libraries we include, we don't use the semicolon. Not sure why it would be necessary here.

2022-11-08 13:17 UTC, paulbourelly999 commented on signal_opt_service/include/signal_opt_processing_worker.h
> +         * shall be at least 1.
**NON CRITICAL** Does this method throw an exception if less than one fixed movement group is represent in the spat? If so may want to add a @throws description of when this method will throw an exception. Also as an external person it may be helpful to know what is considered a fixed movement group. 
```
A fixed movement group is 1 or 2 signal groups in the spat having a future or current protected movement event with a start and end time.
```

2022-11-08 13:25 UTC, paulbourelly999 commented on signal_opt_service/manifest.json
> +            "name": "dpp_producer_sleep_time",
Signal Optimization Interval or Signal Optimization Frequency or Signal Optimization Phase Decision Frequency. Sleep time tells very little about what the configuration property does. Also please update the description to include a description of what this property changes so that someone familiar with SO but maybe not our internal implementation could figure out what this property controls.

2022-11-08 13:26 UTC, paulbourelly999 commented on signal_opt_service/manifest.json
> +            "value": 1000,
Is 1 second a reasonable default value?

2022-11-08 13:28 UTC, paulbourelly999 commented on signal_opt_service/manifest.json
> +            "description": "The configurable time interval in milliseconds defined to account for entering time (ET) estimation inaccuracy.",
Just for my own knowledge, what specifically will this buffer impact?

2022-11-08 13:30 UTC, paulbourelly999 commented on signal_opt_service/manifest.json
> +            "value": 3000,
No the purpose of the parameter is that we can use it to account for queuing vehicles. Since we don't have queuing vehicle we don't need it to have a default value. My outlook on this is that a 0 default value is better than an arbitrary default value, especially one who's impact we don't clearly know yet.

2022-11-08 13:32 UTC, paulbourelly999 commented on signal_opt_service/manifest.json
> +            "value": 5000,
tsc config has a min green for each phase and and a max green for each phase. I assume we are using this as a general configuration for all SG that overrides the values set on the TSC. One thing we have to keep an eye on, also may be worth mentioning in the description is that any min green set here needs to be >= the min green set for any active phase on the controller, or else it won't be achievable.

2022-11-08 13:34 UTC, paulbourelly999 commented on signal_opt_service/src/signal_opt_processing_worker.cpp
> +            SPDLOG_DEBUG("dpp_generator_ptr is not initialized!");
If the dpp generator is not initialized should we be throwing and exception or at least logging something higher than info. The method that calls this, would it fail if given an empty desired phase plan. If so, we may as well throw an exception here.

2022-11-08 13:36 UTC, paulbourelly999 commented on signal_opt_service/src/signal_opt_processing_worker.cpp
> +        SPDLOG_DEBUG("so_processing_worker - dpp_generator start!");
Could we replace these log statements with something more informative. What are we trying to capture here?

2022-11-08 13:39 UTC, paulbourelly999 commented on signal_opt_service/src/signal_opt_processing_worker.cpp
> +        bool enable_so_logging = streets_service::streets_configuration::get_boolean_config("enable_so_logging");
**NON CRITICAL** Next time it is probably better to pass this boolean parameter in from the service level. Even though we have access to the configurations throughout the code I think it is good practice to try and organize configuration calls into a common place so that people looking through our code know where to look for stuff. It does not make any functional difference but I think since we have almost all our configuration calls in service classes for all of our CARMA-Streets Services, this is a good practice to keep up.

2022-11-08 13:41 UTC, paulbourelly999 commented on signal_opt_service/src/signal_opt_service.cpp
> +                configure_csv_logger();
Can this method fail, if so, what do we want to do on failure.

2022-11-08 13:45 UTC, paulbourelly999 commented on signal_opt_service/src/signal_opt_service.cpp
> +                exit(EXIT_FAILURE);
**NON Critical** I am not a fan of initialize methods that can call exit and can return false. We should pick one. I prefer we return a boolean and allow the calling file to decide how to proceed based on the state of initialization.  I this case we would return false for kafka initialization issues and main.cpp would call exit on false returns.

2022-11-08 13:46 UTC, paulbourelly999 commented on signal_opt_service/src/signal_opt_service.cpp
> +        SPDLOG_DEBUG("Starting desired phase plan producer thread.");
Not a useful log statement

2022-11-08 13:50 UTC, paulbourelly999 commented on signal_opt_service/src/signal_opt_service.cpp
> +        int sleep_millisecs = streets_service::streets_configuration::get_int_config("dpp_producer_sleep_time");
**NON CRITICAL** See earlier comment about retrieving configuration values in a common place.

2022-11-08 13:54 UTC, paulbourelly999 commented on signal_opt_service/src/signal_opt_service.cpp
> +            streets_desired_phase_plan::streets_desired_phase_plan spat_dpp = _so_processing_worker_ptr->convert_spat_to_dpp(_spat_ptr, _movement_groups_ptr);
If this currently returns an empty desired phase plan we will still try to run the rest of the functions. What will happen if we try to run the other functions with an empty desired phase plan. If we want to guard against this either make `convert_spat_to_dpp` throw an exception when  dpp generator is not initialized or something fails and catch that exception here or add java doc comment that outlines that  method will return empty desired phase plan if dpp_generator is not initialized or something fails and add a check here to ignore cases in which that happens

2022-11-08 13:55 UTC, paulbourelly999 commented on signal_opt_service/src/signal_opt_service.cpp
> +        dpp_config.initial_green_buffer = streets_service::streets_configuration::get_int_config("initial_green_buffer");
**NON CRITICAL** See earlier comment about retrieving configuration parameter in a common place. Currently that is the initialize() method for most of our service.

2022-11-08 13:59 UTC, paulbourelly999 commented on signal_opt_service/test/test_signal_opt_processing_worker.cpp
> +            std::string json_info = "{\"departure_lanelets\":[{ \"id\":11, \"length\":41.609524398391133, \"speed_limit\":11.176}, { \"id\":12, \"length\":189.445653026013676, \"speed_limit\":11.176
**NON CRITICAL** This is fine for now since we do it in other places as well but for the future we should move away from including single line giant JSON like this. It is not readable. Either we should add it to a file and read from there or indent it in a way that makes it readable.

2022-11-08 14:08 UTC, paulbourelly999 commented on streets_utils/streets_signal_optimization/src/streets_desired_phase_plan_arbitrator.cpp
> +                // Add those vehicles that are within SO radius to schedule_ptr
**NON CRITICAL** update to
```
Add vehicle schedules from all_schedule_ptr for vehicle that are in SO area.
```

2022-11-08 14:10 UTC, paulbourelly999 commented on streets_utils/streets_signal_optimization/src/streets_desired_phase_plan_arbitrator.cpp
> +                float delay_measure = calculate_delay_measure(schedule_ptr, candidate_dpp, enable_so_logging);
**NON CRITICAL** Ideally this would be a private member that you can set on the class in one place instead of making it a parameter that has to be passed into multiple methods. Non critical though

2022-11-08 14:12 UTC, paulbourelly999 commented on streets_utils/streets_signal_optimization/src/streets_desired_phase_plan_arbitrator.cpp
> +                    logger->info( "\n" );
Why? We have to be better with formatting for CSV logs. Also this will create two empty lines which is definitely redundant. I almost prefer no empty lines and us having to use timestamps to differentiate runs because it makes the log files smaller and more concise. We can always using parsing logic to parse out runs based on some timing or state information.

2022-11-08 14:17 UTC, paulbourelly999 commented on streets_utils/streets_signal_optimization/src/streets_desired_phase_plan_arbitrator.cpp
> +        for (const auto &move_group : candidate_dpp.desired_phase_plan) {
So this information will change in length based on the length of the desired phase plan. Lets move all other constant length information about this for parsing. This can then be used purely as additional information we can manually use for debugging.

2022-11-08 14:19 UTC, paulbourelly999 commented on streets_utils/streets_signal_optimization/src/streets_desired_phase_plan_arbitrator.cpp
> +        for (const auto &move_group : candidate_dpp.desired_phase_plan) {
Alternatively we can also have this be a single comma separated value that is a string JSON payload. We still want it at the end. Something like this :

```
val, constant_length_value, constant length value , "{desired_phase_plan json}"
```

2022-11-08 14:27 UTC, paulbourelly999 commented on streets_utils/streets_signal_optimization/test/test_streets_desired_phase_plan_arbitrator.cpp
> +                throw streets_vehicles::status_intent_processing_exception("vehicle update is not array!");
See earlier comment about error handling in unit tests. It is not necessary to throw exceptions in unit testing helper functions but if you do it only makes sense if you include some sort of error handling in the test case that call the helper method to fail or do something when the helper method throws and exception.

2022-11-08 14:30 UTC, paulbourelly999 requested changes
Great job with the mock kafka producer. Most of this looks good. So some small stuff and then some non critical stuff. Also gave some future pointers. Looks like more work than we initially anticipated. Thanks for doing it. Feel free to use your digression for the non critical stuff. Just leave a comment for the ones you address.

2022-11-08 15:08 UTC, Saeid-Solei commented on signal_opt_service/manifest.json
> +            "name": "dpp_producer_sleep_time",
Done!

2022-11-08 15:08 UTC, Saeid-Solei commented on signal_opt_service/manifest.json
> +            "value": 2000,
Done!

2022-11-08 15:13 UTC, Saeid-Solei commented on signal_opt_service/manifest.json
> +            "value": 3000,
Done!

2022-11-08 15:17 UTC, Saeid-Solei commented on signal_opt_service/src/signal_opt_service.cpp
> +        SPDLOG_INFO("Starting desired phase plan producer thread.");
Changed to DEBUG.

2022-11-08 15:18 UTC, Saeid-Solei commented on streets_utils/streets_signal_optimization/src/streets_desired_phase_plan_arbitrator.cpp
> +                    logger->info( "\n" );
Sure, I have removed this extra line.

2022-11-08 15:19 UTC, Saeid-Solei commented on streets_utils/streets_signal_optimization/src/streets_desired_phase_plan_arbitrator.cpp
> +        std::string so_info = "";
I have removed the field names.

2022-11-08 15:19 UTC, Saeid-Solei commented on streets_utils/streets_signal_optimization/src/streets_desired_phase_plan_arbitrator.cpp
> +        so_info += "\n";
Removed "\n" line.

2022-11-08 15:20 UTC, Saeid-Solei commented on streets_utils/streets_signal_optimization/test/test_streets_desired_phase_plan_arbitrator.cpp
> +                SPDLOG_ERROR("vehicle update is not array!");
Removed SPDLOG_ERROR.

2022-11-08 15:29 UTC, Saeid-Solei commented on signal_opt_service/include/signal_opt_processing_worker.h
> +        void configure_dpp_optimizer(const streets_signal_optimization::streets_desired_phase_plan_generator_configuration &dpp_config);
Done!

2022-11-08 15:30 UTC, Saeid-Solei commented on signal_opt_service/include/signal_opt_processing_worker.h
> +         * @brief Convert the provided intersection_state to a desired phase plan. The number of fixed future movement groups
Good catch. I have copied this description from streets_desired_phase_plan_generator. Revised.

2022-11-08 15:33 UTC, Saeid-Solei commented on signal_opt_service/include/signal_opt_processing_worker.h
> +         * shall be at least 1.
The streets_desired_phase_plan_generator library will throw an exception if the number of fixed movement group is 0. Would adding a try\catch method in signal_opt_service fix the issue? Also, since we explained when the streets_desired_phase_plan_generator library throws an exception, do we need to include the throws description here as well?

2022-11-08 15:39 UTC, dan-du-car submitted a review, later dismissed

2022-11-08 15:39 UTC, Saeid-Solei commented on signal_opt_service/include/signal_opt_service.h
> +         * @brief Method to produce desired phase plan to kafka producer.
Done!

2022-11-08 15:41 UTC, Saeid-Solei commented on signal_opt_service/manifest.json
> +            "value": 1000,
Technically, since our min_green is around 5 secs, we could increase this value. I have no preference here, but I want to make sure that the signal optimization service has at least 2 chances to send a desired phase plan during one green phase.

2022-11-08 15:44 UTC, Saeid-Solei commented on signal_opt_service/manifest.json
> +            "description": "The configurable time interval in milliseconds defined to account for entering time (ET) estimation inaccuracy.",
When calculating the required green duration for each entry lane, this buffer will be added to the estimated ET of the last vehicle from a queue. Basically, the end time of the required green will be:

end time of the green = ET of last vehicle in the queue + et_inaccuracy_buffer + final_green_buffer.

2022-11-08 15:46 UTC, Saeid-Solei commented on signal_opt_service/src/signal_opt_processing_worker.cpp
> +            SPDLOG_DEBUG("dpp_generator_ptr is not initialized!");
So, the library will throw an exception if the desired_phase_plan is empty. But I agree that here we should also throw an exception and do not continue. I have added a throw statement here and will catch it in signal_opt_service.

2022-11-08 15:47 UTC, Saeid-Solei commented on signal_opt_service/src/signal_opt_processing_worker.cpp
> +        SPDLOG_DEBUG("so_processing_worker - dpp_generator start!");
I have added these when debugging. I forgot to remove them. I have removed them now.
Please let me know if you think a log statement here is necessary.

2022-11-08 15:52 UTC, Saeid-Solei commented on signal_opt_service/src/signal_opt_service.cpp
> +                configure_csv_logger();
I am not sure if it will fail. If it does, this method will catch the failure. We did not have any separate try\catch for this method in scheduling_service. So, I thought this should be okay.

2022-11-08 22:30 UTC, paulbourelly999 commented on signal_opt_service/include/signal_opt_processing_worker.h
> +         * shall be at least 1.
Oh I missed that. If a lower method already throws an exception for this no need to add any additional exceptions. It is always nice to have documentation that is complete and independent of other methods documentation so including is good but not required I guess.

2022-11-08 22:30 UTC, paulbourelly999 commented on signal_opt_service/include/signal_opt_processing_worker.h
> +         * shall be at least 1.
I still think a description for fixed movement group is helpful.

2022-11-08 22:36 UTC, Saeid-Solei commented on signal_opt_service/src/signal_opt_service.cpp
> +        SPDLOG_DEBUG("Starting desired phase plan producer thread.");
Removed!

2022-11-08 22:36 UTC, paulbourelly999 commented on signal_opt_service/manifest.json
> +            "value": 1000,
This would give us 5 but that is OK to. Ideally I would think you want this to run a little less frequent so in between runs you are exposed to an entire queue of vehicle instead of just a single on that has newly entered the SO radius

2022-11-08 22:36 UTC, Saeid-Solei commented on signal_opt_service/src/signal_opt_service.cpp
> +        int sleep_millisecs = streets_service::streets_configuration::get_int_config("dpp_producer_sleep_time");
Addressed!

2022-11-08 22:36 UTC, Saeid-Solei commented on signal_opt_service/src/signal_opt_service.cpp
> +        dpp_config.initial_green_buffer = streets_service::streets_configuration::get_int_config("initial_green_buffer");
Addressed!

2022-11-08 22:37 UTC, paulbourelly999 commented on signal_opt_service/manifest.json
> +            "description": "The configurable time interval in milliseconds defined to account for entering time (ET) estimation inaccuracy.",
Hmm, not sure I understand why we separated this from final buffer. It seems to be exactly the same functionality.

2022-11-08 22:38 UTC, paulbourelly999 commented on signal_opt_service/manifest.json
> +            "description": "The configurable time interval in milliseconds defined to account for entering time (ET) estimation inaccuracy.",
Thats fine I guess. Maybe we want to put in an enhancement to remove this redundant configuration property.

2022-11-08 22:39 UTC, Saeid-Solei commented on streets_utils/streets_signal_optimization/src/streets_desired_phase_plan_arbitrator.cpp
> +                float delay_measure = calculate_delay_measure(schedule_ptr, candidate_dpp, enable_so_logging);
Done!

2022-11-08 22:40 UTC, Saeid-Solei commented on signal_opt_service/src/signal_opt_processing_worker.cpp
> +        bool enable_so_logging = streets_service::streets_configuration::get_boolean_config("enable_so_logging");
Done!

2022-11-08 22:47 UTC, Saeid-Solei commented on signal_opt_service/test/test_data/updates_signalized.json
>                  "cur_speed": 5.0,
addressed.

2022-11-08 22:50 UTC, Saeid-Solei commented on signal_opt_service/test/test_signal_opt_processing_worker.cpp
> +                throw streets_vehicles::status_intent_processing_exception("vehicle update is not array!");
Removed Throw!

2022-11-08 22:52 UTC, Saeid-Solei commented on streets_utils/streets_signal_optimization/src/streets_desired_phase_plan_arbitrator.cpp
> +                schedule_ptr->vehicle_schedules.clear();
Removed!

2022-11-08 22:52 UTC, Saeid-Solei commented on streets_utils/streets_signal_optimization/src/streets_desired_phase_plan_arbitrator.cpp
> +                // Add those vehicles that are within SO radius to schedule_ptr
Done!

2022-11-08 22:56 UTC, Saeid-Solei commented on streets_utils/streets_signal_optimization/test/test_streets_desired_phase_plan_arbitrator.cpp
> +                throw streets_vehicles::status_intent_processing_exception("vehicle update is not array!");
Removed throw.

2022-11-08 23:01 UTC, Saeid-Solei commented on signal_opt_service/manifest.json
> +            "value": 1000,
That is a great and valid point. I agree. We should increase this value. Is 5000 a reasonable value?

2022-11-09 00:14 UTC, Saeid-Solei commented on streets_utils/streets_signal_optimization/src/streets_desired_phase_plan_arbitrator.cpp
> +        for (const auto &move_group : candidate_dpp.desired_phase_plan) {
Done!

2022-11-09 01:56 UTC, Saeid-Solei commented on signal_opt_service/include/signal_opt_processing_worker.h
> +         * shall be at least 1.
I have added the description.

2022-11-09 01:57 UTC, Saeid-Solei commented on signal_opt_service/src/signal_opt_service.cpp
> +                exit(EXIT_FAILURE);
Addressed!

2022-11-09 19:38 UTC, paulbourelly999 commented on signal_opt_service/src/signal_opt_service.cpp
> +                configure_csv_logger();
Good call we have a try catch in the method. That works too.

2022-11-09 19:41 UTC, paulbourelly999 commented on streets_utils/streets_signal_optimization/src/streets_desired_phase_plan_arbitrator.cpp
> +        for (const auto &move_group : candidate_dpp.desired_phase_plan) {
Instead of adding the desired phase plan as comma separated values just add it as a JSON in the last comma separated value as shown above. This way the number of columns in the CSV is constant.

2022-11-10 14:26 UTC, paulbourelly999 commented on signal_opt_service/CMakeLists.txt
> +    streets_service_base_lib::streets_service_base_lib
Will address this later in another PR

2022-11-10 14:28 UTC, paulbourelly999 approved these changes
Looks good to me.

2022-11-10 14:28 UTC, merged