access confirmation request is added
usdot-fhwa-stol/carma-streets pull request #30
Opened 2021-11-05 04:09 UTC by Saeid-Solei

# PR Details
## Description

With the added codes, as soon as the scheduling service gives access to a vehicle, the scheduling service will wait for the vehicle to confirm that it received the access.

Also, a unit test for the vehicle class is added.

## Related Issue

## Motivation and Context
Without this change, the scheduling service might give access to two vehicles with conflicting directions!

## How Has This Been Tested?
The added codes have been tested with a verification test. A set of sample status and intent information for three different vehicles is produced. 

## Types of changes

- [x] Defect fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
[CARMA Contributing Guide](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) 
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-11-08 19:24 UTC, dan-du-car requested changes

2021-11-08 19:31 UTC, dan-du-car commented on scheduling_service/src/main.cpp
> +        veh_sched.AddMember("st", int64_t(schedule.get_stList()[n]*1000), allocator);
Please add comments here why need the conversion?

2021-11-08 21:19 UTC, Saeid-Solei commented on scheduling_service/src/main.cpp
I have added comments here!

2021-11-09 15:20 UTC, dan-du-car commented on scheduling_service/src/main.cpp
Thanks!

2021-11-09 18:22 UTC, dan-du-car approved these changes

2021-11-09 18:22 UTC, merged