Add defaults for environment variables
usdot-fhwa-stol/carma-streets pull request #345
Opened 2023-09-11 13:01 UTC by paulbourelly999

# PR Details
## Description

Adding default values for environment variables to make CARMA Street services more deployable. 
## Related GitHub Issue

## Related Jira Key
[CDAR-332
](https://usdot-carma.atlassian.net/browse/CDAR-332
)

## Motivation and Context
Improve deployment process for CARMA-Streets

## How Has This Been Tested?
Tested using AWS XIL-Cloud deployment

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2023-09-13 14:17 UTC, adamlm requested changes

2023-09-13 14:17 UTC, adamlm commented on streets_utils/streets_service_base/src/streets_service.cpp
>              throw std::runtime_error(" Systme config param name is null pointer!");
This function's implementation needs refactoring. Right now, if the caller passes `nullptr` for `config_name`, the function will throw an error instead of returning `default_val`. Is this the intended behavior? That seems unexpected to me.

We can check for `config_name == nullptr` at the function's beginning and return `default_val` value if `true`. This allows us to avoid throwing a `std::runtime_error`. We can also clean up unnecessary nesting the function's main logic in an `if` statement.

The `try...catch` block pushes the error to the wrong place: the error should be checked on the result of `std::getenv`, not when trying to construct the `std::string`. Function `std::getenv` returns a `nullptr` is the environment variable is not found, so not checking for it is poor practice. See [cppreference](https://en.cppreference.com/w/cpp/utility/program/getenv) for details. We can refactor the main logic into something like this:

```cpp
if (const auto config = std::getenv(config_name) {
    SPDLOG_DEBUG("Reading system config {0} as : {1}!", config_name, config);
    return config;
}

SPDLOG_WARN("System config {0} was not set! Using default value {1}!" ,config_name, default_val);
return default_val;
```
With the above changes, we can also declare `get_system_config` as `noexcept`.

2023-09-13 15:39 UTC, willjohnsonk approved these changes
Looks good

2023-09-13 15:49 UTC, willjohnsonk reviewed
See: Adam's suggestions (was not finished with review when approved)

2023-09-14 15:37 UTC, adamlm requested changes

2023-09-14 15:37 UTC, adamlm commented on streets_utils/streets_service_base/src/streets_service.cpp
> +            return default_val;
The comments above each part of the `if` statements are unnecessary and should be removed. Comments should explain "why" instead of "what." In my opinion, the code here is sufficiently self documenting.

The `else` statement should be removed because it unnecessarily clutters the code. If either `if` statement evaluates to `true`, the contained `return` statements will exit the function early when necessary, so there is no need to scope the final `reutrn`.

There is a bit of code duplication between the `nullptr` and the unset `config_name` cases. I believe we can change the first `if` case's implementation to something like this:

```cpp
if (config_name == nullptr) {
    config_name = "";
}
```

Then we can check `config_name` as if it had been set. The `SPDLOG_WARN` about `nullptr` can then be removed or at least changed to `SPDLOG_DEBUG`.

2023-09-14 15:37 UTC, adamlm commented on streets_utils/streets_service_base/include/streets_environment_variables.h
> +    inline static const std::string DEFAULT_TIME_SYNC_TOPIC = "time_sync";
Remove the `static` declarations. Declaring `inline static` essentially defeats the purpose of using `inline` variables. Check out these two StackOverflow posts for more information: [1](https://stackoverflow.com/questions/50515591/c17-inline-variable-vs-inline-static-variable), [2](https://stackoverflow.com/questions/38043442/how-do-inline-variables-work/47502744#47502744)

2023-09-14 18:30 UTC, adamlm approved these changes

2023-09-14 18:39 UTC, merged