Added JSON Utility Library to carma-streets
usdot-fhwa-stol/carma-streets pull request #352
Opened 2023-09-29 14:54 UTC by paulbourelly999

# PR Details
## Description

Added new json utility library to CARMA Streets.
## Related GitHub Issue

## Related Jira Key
[CDAR-298
](https://usdot-carma.atlassian.net/browse/CDAR-298)

## Motivation and Context
Provide utility methods for parsing json. Possibly in the future this library could abstract away the dependency on third-party json parsing library (rapidjson) to make code more modular and allow for easier transition to other alternative JSON parsing libraries.

## How Has This Been Tested?
Unit testing 

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING**](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-10-02 11:28 UTC, paulbourelly999 commented on streets_utils/json_utils/README.md
> +find_package(streets_utils COMPONENT json_utils)
@adamlm I mentioned this to you a while back but I not been able to figure out the namespace stuff for CMake. If you could help me with this that would be awesome. Currently CMake install installs this package as `json_utils_lib::json_utils_lib". I probably want to move to something more like 'streets_utils::json_utils_lib'. Is it possible to make this change without making it for all the other packages inside streets_utils yet?

2023-10-02 11:34 UTC, paulbourelly999 commented on streets_utils/json_utils/CMakeLists.txt
> +    NAMESPACE ${LIBRARY_NAME}_lib::
Would changing this to using a different namespace be as simple as just changing this namespace parameter? Would it be best practice to make the destination include a parent directory to match the namespace like for example change destination to `lib/cmake/streets_utils/${library_name}_lib/` if we plan on using a namespace like `streets_utils`?

2023-10-02 11:34 UTC, paulbourelly999 commented on streets_utils/json_utils/CMakeLists.txt
> +# Install sensor_data_sharing_package package.
Correct comment

2023-10-02 11:34 UTC, paulbourelly999 commented on streets_utils/json_utils/CMakeLists.txt
> +message( STATUS "Target INCLUDE DIR : " ${INCLUDE_DIRECTORIES})
Remove message

2023-10-02 14:25 UTC, adamlm requested changes

2023-10-02 14:25 UTC, adamlm commented on streets_utils/json_utils/CMakeLists.txt
> +set(CMAKE_CXX_STANDARD 20)
CARMA targets C++17. I've run into issues trying C++20 with other CARMA packages. We should probably stick with C++17 for now.

2023-10-02 14:25 UTC, adamlm commented on streets_utils/json_utils/CMakeLists.txt
> +file(GLOB files ${CMAKE_CURRENT_SOURCE_DIR}/include/*.hpp)
Globbing here is unnecessary. This library has only two header files, so they should be explicitly listed.

2023-10-02 14:25 UTC, adamlm commented on streets_utils/json_utils/CMakeLists.txt
> +set(BINARY ${LIBRARY_NAME}_test)
This is unnecessary. It increases mental overhead without significantly saving on typing. The variable name is also too vague. We should replaced `${BINARY}` with `json_utils_test`.

2023-10-02 14:25 UTC, adamlm commented on streets_utils/json_utils/CMakeLists.txt
> +file(GLOB_RECURSE TEST_SOURCES LIST_DIRECTORIES false test/*.hpp test/*.cpp)
Unnecessary globbing.

2023-10-02 14:25 UTC, adamlm commented on streets_utils/json_utils/CMakeLists.txt
> +set(SOURCES ${TEST_SOURCES} WORKING_DIRECTORY  ${PROJECT_SOURCE_DIR}/test)
Unnecessary variable.

2023-10-02 14:25 UTC, adamlm commented on streets_utils/json_utils/CMakeLists.txt
> +    PUBLIC
This should be marked `PRIVATE` because no downstream entities will link against this.

2023-10-02 14:25 UTC, adamlm commented on streets_utils/json_utils/CMakeLists.txt
> +target_include_directories(${BINARY} PUBLIC ${PROJECT_SOURCE_DIR}/include)
This should be removed. Linking against `json_utils` will provide CMake with information on how to find those headers.

2023-10-02 14:25 UTC, adamlm commented on streets_utils/json_utils/CMakeLists.txt
> +add_test(NAME ${BINARY} COMMAND ${BINARY})
This should be replaced with `gtest_discover_tests()`.

2023-10-02 14:25 UTC, adamlm commented on streets_utils/json_utils/CMakeLists.txt
> +endif()
This is unnecessary. We should either require CMake version 3.20+ and link against `GTest::gtest_main` or use `GTest::Main` for backwards compatibility.

2023-10-02 14:25 UTC, adamlm commented on streets_utils/json_utils/CMakeLists.txt
> +    DESTINATION  lib/cmake/${LIBRARY_NAME}_lib/
This should be `${CMAKE_INSTALL_LIBDIR}/cmake/json_utils`. You will need to `include(GNUInstallDirs)`.

2023-10-02 14:25 UTC, adamlm commented on streets_utils/json_utils/CMakeLists.txt
> +install(FILES ${files} DESTINATION include)
The `DESTINATION` should be `${CMAKE_INSTALL_INCLUDEDIR}/cmake/json_utils`.

2023-10-02 14:25 UTC, adamlm commented on streets_utils/json_utils/include/json_utils.hpp
> +#pragma once
We should use `#include` guards instead of `#pragma once` because the latter is not standard, even though many compilers support it.

2023-10-02 14:25 UTC, adamlm commented on streets_utils/json_utils/include/json_utils_exception.hpp
> +            ~json_utils_exception() = default;
I believe this should be declared `override` since it's overriding `std::runtimte_error`'s destructor.

2023-10-02 14:25 UTC, adamlm commented on streets_utils/json_utils/test/json_utils_test.cpp
> +TEST(json_utils_test, test_validate_invalid_json) {
This violates GTest's naming requirements. Relevant quote from the [documentation](http://google.github.io/googletest/primer.html):

>TEST() arguments go from general to specific. The first argument is the name of the test suite, and the second argument is the test’s name within the test suite. Both names must be valid C++ identifiers, and they should not contain any underscores (_). A test’s full name consists of its containing test suite and its individual name. Tests from different test suites can have the same individual name.

Issue applies to all test cases in this file.

2023-10-02 14:25 UTC, adamlm commented on streets_utils/json_utils/src/json_utils.cpp
> +    }
This function should be refactored to something like `is_valid`. The current implementation does not take any validation steps, it only throws an error if the JSON string is invalid.

2023-10-02 14:47 UTC, paulbourelly999 commented on streets_utils/json_utils/CMakeLists.txt
> +set(LIBRARY_NAME json_utils)
I think this reduces unintentional errors introduces with library name changes or install configuration changes. I also do not think it makes this at all harder to read.

2023-10-02 14:50 UTC, paulbourelly999 commented on streets_utils/json_utils/CMakeLists.txt
> +file(GLOB SOURCES ${CMAKE_CURRENT_SOURCE_DIR}/src/*.cpp)
My thought process for CMakeLists.txt in carma-streets is to attempt to have a similar template that works for any library created. If we were to add another cpp file in the future, a setup like this would avoid any time spent, setting up the CMake config for it.

2023-10-02 16:33 UTC, paulbourelly999 commented on streets_utils/json_utils/CMakeLists.txt
> +########################################################
I think it is helpful to have some kind of separation between the different build/install/test portions of the CMakeLists.txt . I am open to alternative comments or ways of separating this but I don't think there is any disadvantage in having this here

2023-10-02 16:46 UTC, paulbourelly999 commented on streets_utils/json_utils/CMakeLists.txt
> +    TARGETS ${LIBRARY_NAME}_lib
This is a remnant of using project_name as target_name. Will remove and add to library name directly.

2023-10-02 17:13 UTC, paulbourelly999 commented on streets_utils/json_utils/CMakeLists.txt
> +set(BINARY ${LIBRARY_NAME}_test)
I agree that this is vague but not that this variable should be replaced with direct calls to a library name. When setting up these CMakeLists.txt files for different CARMA-Streets libraries I want all the libraries to follow a similar approach for installing, naming convention for targets. This helps a great deal with CI integration later one because instead of 30 independent libraries that each have a CMakeLists.txt that handles installing, naming convention differently, using these variables makes it a lot easier to standup CI to execute tests and do other CI tasks.

With the previous comment, one advantage of using project name to set target names for library and test executable was that it made following a common naming convention easy. With that in mind I kind of what to do something like:

```
project (<project_name)
...
set(LIBRARY_NAME ${PROJECT_NAME}_lib)
...
set(TEST_NAME ${PROJECT_NAME}_test)
```

This would mean our library name and test name are based on our project name but still separate. This way when someone adds project with some name CI processes can rely on the libraries and executables named a certain way. What do you think?

2023-10-02 17:17 UTC, paulbourelly999 commented on streets_utils/json_utils/CMakeLists.txt
> +file(GLOB_RECURSE TEST_SOURCES LIST_DIRECTORIES false test/*.hpp test/*.cpp)
I think this is helpful instead of explicitly naming files since then we have to make CMakeLists.txt changes on every change/addition to test files. Also it allows this CMakeLists.txt to be easily portable to a new streets library.

2023-10-02 17:49 UTC, paulbourelly999 commented on streets_utils/json_utils/CMakeLists.txt
> +file(GLOB files ${CMAKE_CURRENT_SOURCE_DIR}/include/*.hpp)
I think its useful. See other Globbing comments

2023-10-02 18:00 UTC, paulbourelly999 commented on streets_utils/json_utils/include/json_utils.hpp
> +#pragma once
Since we deliver this code as a runnable docker image unless `#pragma once` is being depreciated or we plan on switching to a compiler where this is not supported I do not see the purpose of removing this. In what kind of context would we need to support compiling this library with a compiler that does not support pragma once.

2023-10-02 18:01 UTC, paulbourelly999 commented on streets_utils/json_utils/src/json_utils.cpp
> +    }
Good call.

2023-10-02 22:00 UTC, paulbourelly999 commented on streets_utils/json_utils/include/json_utils.hpp
> +#pragma once
After discussion I think we should table this change until we have a plan for how we want to handle styling. Using pragma once would potentially conflict with ROS standard clang-format which may be the eventual formatting standard we want all our code to adhere to but that is still outstanding.

2023-10-03 13:01 UTC, adamlm commented on streets_utils/json_utils/CMakeLists.txt
> +set(BINARY ${LIBRARY_NAME}_test)
With your suggestion, a library developer can still (unintentionally) set `LIBRARY_NAME` and `TEST_NAME` to something that doesn't follow naming conventions. Having consistent naming across projects is good, but this is not the mechanism to enforce it.

2023-10-03 14:08 UTC, adamlm commented on streets_utils/json_utils/CMakeLists.txt
> +set(LIBRARY_NAME json_utils)
I disagree with the first part of that argument. CMake will throw an error if the target name is undefined. Also, the library name will not change frequently (if ever) after the project is established.

2023-10-03 14:14 UTC, adamlm commented on streets_utils/json_utils/CMakeLists.txt
> +file(GLOB_RECURSE TEST_SOURCES LIST_DIRECTORIES false test/*.hpp test/*.cpp)
I'm not sure what you mean by "easily portable." `CMakeLists.txt` files are specific to the project. If you want some common functionality that can be reused by other projects, it should be wrapped in a function. Adding test files is relatively infrequent compared to changing code implementations within files. Therefore, I don't see a significant utility in globbing here. Globbing prevents you from easily excluding tests for debugging or other purposes.

Another thing I noticed, header files should not added to `TEST_SOURCES`.

2023-10-03 14:33 UTC, paulbourelly999 commented on streets_utils/json_utils/CMakeLists.txt
> +set(LIBRARY_NAME json_utils)
Not if it is undefine but say if you type the library name correctly for target but slightly incorrectly for the directory to install in there is no error. Or you type the cmake config in file name slightly different than the library name or any other small change

2023-10-03 14:36 UTC, paulbourelly999 commented on streets_utils/json_utils/CMakeLists.txt
> +file(GLOB SOURCES ${CMAKE_CURRENT_SOURCE_DIR}/src/*.cpp)
I do not think explicit sources makes it more readable. In fact I think it makes it less readable. All the files in source should automatically be included. If you have a package with a single source that compiles into several dependent targets you should just separate them into separate directories. I think that is the most readable approach. Although I think calling it library_name sources is a good improvement to avoid name conflicts.

2023-10-03 14:36 UTC, paulbourelly999 commented on streets_utils/json_utils/include/json_utils_exception.hpp
> +        using std::runtime_error::runtime_error;
This seems less verbose and was a recommend change from sonar scanner for extending the runtime_error

2023-10-03 14:49 UTC, adamlm commented on streets_utils/json_utils/CMakeLists.txt
> +set(LIBRARY_NAME json_utils)
Configuration issues would/should be discovered when doing a test install locally. That part of the configuration is unlikely to change, so I don't think that part of the argument is strong. I've gone through CMake projects before that use a lot of variables like this, and it made understanding all of the configurations/targets challenging. For a rather simple project like this, it probably does not make a difference. However, if we are trying to establish common conventions across all our projects, the variable approach is not scalable.

2023-10-03 14:58 UTC, adamlm commented on streets_utils/json_utils/include/json_utils_exception.hpp
> +        using std::runtime_error::runtime_error;
Makes sense. I was not aware of this technique before, but it appears to be a standard/best practice.

2023-10-03 16:23 UTC, adamlm approved these changes

2023-10-03 16:23 UTC, merged