Adding streets_messages library which will house JSON serialization
usdot-fhwa-stol/carma-streets pull request #353
Opened 2023-10-04 04:56 UTC by paulbourelly999

deserialization functions and carma-streets messages. This is the new proposed package to store all carma-streets internal messages in.

# PR Details
## Description

## Related GitHub Issue

## Related Jira Key
[CDAR-298
](https://usdot-carma.atlassian.net/browse/CDAR-298)

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING**](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-10-04 15:42 UTC, adamlm requested changes

2023-10-04 15:42 UTC, adamlm commented on streets_utils/streets_messages/include/messages/sensor_data_sharing_msg/detected_object_data_common.hpp
> +        u_int8_t _classification_confidence;
This should be replaced with `std::uint8_t`. The `u_int8_t` type is non-standard C++ and therefore not portable. I can't even find a definitive source on the `u_intN_t` types, but [here](https://lists.freedesktop.org/archives/release-wranglers/2004-August/000923.html) is the closest thing I could find.

2023-10-04 15:42 UTC, adamlm commented on streets_utils/streets_messages/include/messages/sensor_data_sharing_msg/acceleration_confidence_set_4_way.hpp
> +        acceleration_confidence _longitudinal_confidence;
Public member variables should not have a prepended underscore. It should be `longitudinal_confidence`. This applies to several areas.

2023-10-04 17:22 UTC, paulbourelly999 commented on streets_utils/streets_messages/include/messages/sensor_data_sharing_msg/acceleration_confidence_set_4_way.hpp
> +        acceleration_confidence _longitudinal_confidence;
I was conflicted about this. I know traditionally I think sometimes the underscore it used to indicate private members but it also helps avoid naming conflicts with variables and data types. I think in this case its not an issue but for a lot of data types it is. I would generally prefer this to some random shorting of the variable name.

2023-10-04 17:26 UTC, paulbourelly999 commented on streets_utils/streets_messages/CMakeLists.txt
> +    target_link_libraries( ${TEST_NAME} PUBLIC gtest_main )
I think newer versions of Google test are not backwards compatible. What I mean it that if you have CMake version greater than 3.20 which is the case for any ubuntu 22 images I do not think it is able to correctly link . I think I remember this being an issue. Since we are using some of these libraries in different ubuntu distributions and we use the default versions of CMake that come with the distribution I made this fix

2023-10-04 18:14 UTC, adamlm commented on streets_utils/streets_messages/CMakeLists.txt
> +    target_link_libraries( ${TEST_NAME} PUBLIC gtest_main )
I tried it in an Ubuntu 22.04 environment and didn't have an issue. The FindGTest.cmake module documentation shows that `GTest::Main` has been deprecated, but it has not been removed in any CMake version yet.

2023-10-04 18:18 UTC, adamlm commented on streets_utils/streets_messages/include/messages/sensor_data_sharing_msg/acceleration_confidence_set_4_way.hpp
> +        acceleration_confidence _longitudinal_confidence;
I suggest avoiding underscores until it is necessary.

2023-10-04 19:07 UTC, paulbourelly999 commented on streets_utils/streets_messages/include/deserializers/sensor_data_sharing_msg_json_deserializer.hpp
> +#include "messages/sensor_data_sharing_msg/sensor_data_sharing_msg.hpp"
I want to understand this a little more. Is this related to the installation process. If so, do I need to specific streets_utils as well.

2023-10-04 19:10 UTC, paulbourelly999 commented on streets_utils/streets_messages/CMakeLists.txt
> +    target_link_libraries( ${TEST_NAME} PUBLIC gtest_main )
OK I will try this again. Can you tell me what version of gtest you were using and how you installed it. I think I remember installing the debian package using apt will skip some cmake necessary steps that you then have to run after.

2023-10-04 20:08 UTC, adamlm commented on streets_utils/streets_messages/include/messages/sensor_data_sharing_msg/acceleration_confidence.hpp
> +        ACCL_0_01 = 7     // 0.01 m/s^2
I see what you're saying. I was suggesting that we drop the enumeration values if they are unneeded and go with something like this:

```cpp
enum class acceleration_confidence {
  UNAVAILABLE,
  ACCL_100,
  // ...
};
```

But if we actually need them, then we can ignore my comment.

2023-10-05 13:02 UTC, adamlm commented on streets_utils/streets_messages/include/deserializers/sensor_data_sharing_msg_json_deserializer.hpp
> +#include "messages/sensor_data_sharing_msg/sensor_data_sharing_msg.hpp"
It involves moving all the directories in `include/` to `include/streets_messages/`. It's somewhat related to installation, but the point of the suggestion was to have a more unique root directory for the header files. `messages` is rather vague and could collide with other projects.

2023-10-10 14:29 UTC, paulbourelly999 commented on streets_utils/streets_messages/CMakeLists.txt
> +    target_link_libraries( ${TEST_NAME} PUBLIC gtest_main )
Ok I tried this and the linker is no longer able to find definitions for google test
```
target_link_libraries( ${TEST_NAME}  PRIVATE gtest_main)
```

Some of the error text:
```
build] /usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/11/../../../x86_64-linux-gnu/libgtest_main.a(gtest_main.cc.o): in function `main':
[build] (.text.startup+0x33): undefined reference to `testing::InitGoogleTest(int*, char**)'
[build] /usr/bin/ld: (.text.startup+0x38): undefined reference to `testing::UnitTest::GetInstance()'
[build] /usr/bin/ld: (.text.startup+0x40): undefined reference to `testing::UnitTest::Run()'
[build] /usr/bin/ld: CMakeFiles/streets_messages_lib_test.dir/test/sensor_data_sharing_msg_json_deserialization_test.cpp.o: in function `sensor_dara_sharing_msg_json_deserialization_test_deserialize_Test::TestBody()':
[build] /home/dev/carma-streets/streets_utils/streets_messages/test/sensor_data_sharing_msg_json_deserialization_test.cpp:71: undefined reference to `testing::internal::AlwaysTrue()'
[build] /usr/bin/ld: /home/dev/carma-streets/streets_utils/streets_messages/test/sensor_data_sharing_msg_json_deserialization_test.cpp:71: undefined reference to `testing::Message::Message()'
[build] /usr/bin/ld: /home/dev/carma-streets/streets_utils/streets_messages/test/sensor_data_sharing_msg_json_deserialization_test.cpp:71: undefined reference to `testing::internal::AssertHelper::AssertHelper(testing::TestPartResult::Type, char const*, int, char const*)'
[build] /usr/bin/ld: /home/dev/carma-streets/streets_utils/streets_messages/test/sensor_data_sharing_msg_json_deserialization_test.cpp:71: undefined reference to `testing::internal::AssertHelper::operator=(testing::Message const&) const'
[build] /usr/bin/ld: /home/dev/carma-streets/streets_utils/streets_messages/test/sensor_data_sharing_msg_json_deserialization_test.cpp:71: undefined 
```

I cannot link against GTest::gtest_main since this will not work for CMake versions < 3.20 which some of our carma-streets services are limited to due to ubuntu distributions.

Please let me know if you think I am doing something incorrect. We could eventually edit CI/docker build process to point any ubuntu distro we use to a common CMake version but that is definitely more work that just using this if.

2023-10-10 14:30 UTC, paulbourelly999 commented on streets_utils/streets_messages/include/messages/sensor_data_sharing_msg/acceleration_confidence.hpp
> +        ACCL_0_01 = 7     // 0.01 m/s^2
We do need them since the JSON uses them instead of a string representation.

2023-10-10 19:12 UTC, paulbourelly999 commented on streets_utils/streets_messages/include/deserializers/sensor_data_sharing_msg_json_deserializer.hpp
> +    sensor_data_sharing_msg from_json( const std::string &val);
@adamlm When we spoke a while ago, you mentioned there was some templated approach to defining these non-member functions to create a kind of "compile time inheritance". What would that look like? Is there a way to define the templated function something like
```
<template class sensor_data_sharing_msg>
sensor_data_sharing_msg from_json(const std::string &val) ...
```
so that I have only defined a function from json to return a sensor data sharing message? If I implement a new function for a new message, how would C++ determine which to use without inheritance?

2023-10-11 21:31 UTC, adamlm commented on streets_utils/streets_messages/CMakeLists.txt
> +    target_link_libraries( ${TEST_NAME} PUBLIC gtest_main )
If you need support for CMake before 3.20, you should use `GTest::Main`, which is equivalent to `GTest::gtest_main`.

2023-10-12 21:09 UTC, paulbourelly999 commented on streets_utils/streets_messages/include/deserializers/sensor_data_sharing_msg_json_deserializer.hpp
> +    sensor_data_sharing_msg from_json( const std::string &val);
Move to github enhancement (https://github.com/usdot-fhwa-stol/carma-streets/issues/356)

2023-10-19 14:15 UTC, adamlm requested changes

2023-10-19 14:40 UTC, paulbourelly999 commented on streets_utils/json_utils/CMakeLists.txt
> +    DESTINATION include/streets_utils/${LIBRARY_NAME}
Good catch

2023-10-19 14:41 UTC, paulbourelly999 commented on streets_utils/json_utils/CMakeLists.txt
>  else()
Hmm I removed this and I am using GTest::Main. No idea why git diff is showing this.

2023-10-19 14:44 UTC, paulbourelly999 commented on streets_utils/streets_messages/cmake/streets_messages_libConfig.cmake.in
> +include("${CMAKE_CURRENT_LIST_DIR}/sensor_data_sharing_msg_libTargets.cmake")
good catch

2023-10-19 14:47 UTC, paulbourelly999 commented on streets_utils/streets_messages/include/sensor_data_sharing_msg/acceleration_confidence.hpp
> +    inline acceleration_confidence acceleration_confidence_from_int( const unsigned int i ) {
My thought process was that without this function there would be no need to even define a cpp file so I defined it inline here. If this was a more complex struct or there were multiple functions then I would move definition to cpp but this felt appropriate here.

2023-10-19 14:49 UTC, paulbourelly999 commented on streets_utils/streets_messages/src/deserializers/sensor_data_sharing_msg_json_deserializer.cpp
> +    sensor_data_sharing_msg from_json( const std::string &json ){
Plan is to move to https://github.com/usdot-fhwa-stol/carma-streets/issues/356 for remove ambiguity.

2023-10-19 15:44 UTC, paulbourelly999 commented on streets_utils/streets_messages/include/sensor_data_sharing_msg/detected_object_data_common.hpp
> +        unsigned int  _object_id;
My thought process here is that the data type of the fields indicates valid value range. I can see that blindly assigning values to this member introduces some risks in terms of negative values creating unexpected behavior. I was thinking that it would be on the user of this data structure to ensure they are populating this struct with correct data. In the future, we could setup some common mechanisms by which to clamp or validate input data but as currently input we either allow the data struct to have invalid values that maybe more easily diagnosable retroactively but may not give users  as much initial guidance on valid values. Or we use unsigned int which may discourage users from assign negative values more but becomes harder to diagnose when negative values are unintentionally assigned. 

If we did eventually add clamping or range checks with exceptions, would that just be creating setter methods or is that done differently. I ask because I think changing this either way is only valuable if it makes or planned approach substantially easier. Otherwise I am not sure how impactful this is

2023-10-19 16:00 UTC, willjohnsonk reviewed
Update message fields to initialize as their UNAVAILABLE/UNKOWN value prior to setting them in case they contain garbage/empty data

2023-10-19 19:04 UTC, paulbourelly999 commented on streets_utils/streets_messages/include/sensor_data_sharing_msg/angular_velocity_confidence.hpp
> +    inline angular_velocity_confidence angular_velocity_confidence_from_int( const unsigned int i ){
See angular velocity confidence set. That is the struct that contains the 2 enumerations for pitch confidence and roll rate confidence

2023-10-19 19:24 UTC, paulbourelly999 commented on streets_utils/streets_messages/include/sensor_data_sharing_msg/time_stamp.hpp
> +    struct time_stamp {
I do not think the naming here is terribly important. I considered the entire data structure required from our perspective since publishing a SDSM without a timestamp is meaningless in our cooperative perception scenario.

2023-10-19 19:51 UTC, paulbourelly999 commented on streets_utils/streets_messages/include/sensor_data_sharing_msg/acceleration_confidence.hpp
> +        }
Updated

2023-10-19 19:53 UTC, paulbourelly999 commented on streets_utils/streets_messages/include/sensor_data_sharing_msg/vehicle/vehicle_size.hpp
> +    struct vehicle_size {
I do not understand this comment. This is the type defined in the SDSM message/j2735 spec. What would you want it to be consistent with.

2023-10-19 21:15 UTC, adamlm requested changes
One minor change.

2023-10-19 21:15 UTC, adamlm commented on streets_utils/streets_messages/include/sensor_data_sharing_msg/sensor_data_sharing_msg.hpp
> +        unsigned int  _msg_count;
This should be changed to a `std::size_t`.

2023-10-19 21:17 UTC, paulbourelly999 commented
> Update message fields to initialize as their UNAVAILABLE/UNKOWN value prior to setting them in case they contain garbage/empty data

Addressed

2023-10-19 21:19 UTC, willjohnsonk requested changes
Update message fields to initialize as their UNAVAILABLE/UNKOWN value prior to setting them in case they contain garbage/empty data

(previously did not tag as requested change)

2023-10-19 21:31 UTC, adamlm approved these changes

2023-10-19 21:34 UTC, adamlm commented on streets_utils/streets_messages/include/sensor_data_sharing_msg/detected_object_data_common.hpp
> +        unsigned int  _object_id;
Ideally, we would replace `int`, `float`, _etc_. primitives with range-bounded types that throw exceptions or clamp values beyond their range.

2023-10-20 13:13 UTC, willjohnsonk approved these changes

2023-10-20 14:39 UTC, paulbourelly999 commented on streets_utils/streets_messages/include/sensor_data_sharing_msg/detected_object_data_common.hpp
> +        unsigned int  _object_id;
Agreed, i think that can be added in the future.

2023-10-20 14:40 UTC, merged