Initial commit for sensor data sharing service.
usdot-fhwa-stol/carma-streets pull request #363
Opened 2023-11-14 22:09 UTC by paulbourelly999

# PR Details
## Description

## Related GitHub Issue

## Related Jira Key

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING**](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-11-27 22:01 UTC, adamlm requested changes

2023-11-27 22:01 UTC, adamlm commented on sensor_data_sharing_service/build.sh
> +done
Is there a reason we're using `make` directly instead of CMake's commands?

2023-11-28 04:09 UTC, paulbourelly999 commented on sensor_data_sharing_service/src/sensor_data_sharing_service.cpp
> +                const std::string json_msg = to_json(msg);
This will be removed entirely in final PR. It is just for integration testing purposes.

2023-11-28 13:42 UTC, paulbourelly999 commented on sensor_data_sharing_service/include/sensor_data_sharing_service.hpp
> +            sds_service& operator=(const sds_service &) = delete;
There are not need. We do not need a copy constructor or a copy assignment constructor. We do not want this service class created using anything but the regular constructor. Implementing these other copy constructors encourages incorrect use of this service while requiring additional effort to ensure the base class functionality also still works.

2023-11-28 13:43 UTC, paulbourelly999 commented on sensor_data_sharing_service/test/sensor_data_sharing_service_test.cpp
> +TEST(sensor_data_sharing_service_test, test_initialize) {
Removing the underscores? I can do that

2023-11-28 15:47 UTC, paulbourelly999 commented on sensor_data_sharing_service/src/sensor_data_sharing_service.cpp
> +    }
This does not work. The streets service initial configures the singleton for access to streets_configurations. I should probably move logging calls after this as well since the file logger is setup in this initialize method as well.

2023-11-29 18:45 UTC, paulbourelly999 commented on sensor_data_sharing_service/src/sensor_data_sharing_service.cpp
> +        if (sdsm_producer)
I kind of disagree with this. I think this is pretty command and easy to read.  I can change in smaller conditions but in complex conditions this looks noisy and more confusing. My inclination is to leave this as is for consistency. Unless there is some C++ ISO guidelines that say otherwise

2023-11-29 18:50 UTC, paulbourelly999 commented on sensor_data_sharing_service/src/sensor_data_sharing_service.cpp
> +    using namespace streets_utils::messages;
https://jmmv.dev/2013/12/header-files-avoid-c-using-directives.html#:~:text=To%20recap%2C%20using%20directives%20in,headers%20and%20their%20possible%20conflicts.  This kind of reflects my view on this. The focus being to avoid using namespace in header files and with external namespaces. In my opinion it makes code easier to read because it strips extraneous namespaces from method/function calls. Using an IDE the source is still very easy to trace. Even using github web UI it is able to find the method definition by searching the rest of the repository.

2023-11-29 18:59 UTC, paulbourelly999 commented on sensor_data_sharing_service/src/sensor_data_sharing_service.cpp
> +    using namespace streets_utils::messages;
One additional issue here is that currently we have a class and a namespace which share a name.  `streets_service` I think this causes issues when attempting to include things from the namespace and call base class service methods. This is probably something I should address independently. I create the following issue for that (https://github.com/usdot-fhwa-stol/carma-streets/issues/371)

2023-11-29 18:59 UTC, paulbourelly999 commented on sensor_data_sharing_service/src/sensor_data_sharing_service.cpp
> +        if(detection_consumer)
See response.

2023-11-29 19:08 UTC, adamlm requested changes

2023-11-29 19:08 UTC, adamlm commented on sensor_data_sharing_service/build.sh
> +    "streets_utils/streets_service_configuration"\
Why is this line continuation here?

2023-11-29 19:12 UTC, adamlm commented on sensor_data_sharing_service/src/sensor_data_sharing_service.cpp
> +        if (sdsm_producer)
I checked the C++ ISO guidelines, and I'm completely wrong. They actively discourage what I suggested: https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#es87-dont-add-redundant--or--to-conditions.

2023-11-29 19:12 UTC, adamlm commented on sensor_data_sharing_service/src/sensor_data_sharing_service.cpp
> +        if(detection_consumer)
Same response as above.

2023-11-29 19:13 UTC, adamlm commented on sensor_data_sharing_service/src/sensor_data_sharing_service.cpp
> +            while ( detection_consumer && detection_consumer->is_running() ) {
Same response as related comments.

2023-11-29 21:53 UTC, adamlm commented on sensor_data_sharing_service/src/sensor_data_sharing_service.cpp
> +    using namespace streets_utils::messages;
I didn't find that blog post particularly compelling. It claims that using-directives are fine excluding some small technical issues. However, the Abseil library's blog post provides a more comprehensive overview of the issues `using namespace ...` can cause:https://abseil.io/tips/153.

I recommend we follow Abseil's guidance and remove `using namespace ...`.

2023-11-29 22:23 UTC, paulbourelly999 commented on sensor_data_sharing_service/src/main.cpp
> +    catch ( const std::runtime_error &e) {
I think this is more of a catch all for generic unexpected/uncaught exceptions, to make sure we log the exception message. My understanding is that in C++ if an exception is uncaught, the message will not be printed. This is sort of a fail safe for any uncaught exception.

2023-11-30 06:52 UTC, paulbourelly999 commented on sensor_data_sharing_service/src/sensor_data_sharing_service.cpp
> +    using namespace streets_utils::messages;
Resolved using namespace aliasing which seems to be OK according to this post. Not sure what the difference is currently but will have to read more when I have some down time.

2023-11-30 14:20 UTC, adamlm requested changes

2023-11-30 14:47 UTC, paulbourelly999 commented on sensor_data_sharing_service/src/main.cpp
> +    catch ( const std::runtime_error &e) {
Good call. Done.

2023-11-30 15:22 UTC, adamlm approved these changes

2023-11-30 15:40 UTC, merged