updates
usdot-fhwa-stol/carma-streets pull request #364
Opened 2023-11-15 15:43 UTC by paulbourelly999

# PR Details
## Description

## Related GitHub Issue

## Related Jira Key

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING**](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-11-15 22:49 UTC, paulbourelly999 commented on streets_utils/streets_service_base/CMakeLists.txt
> +    DISCOVERY_MODE PRE_TEST
Had to add this property to avoid the following CI error when attempting to run test executable.
```
/home/carma-streets/streets_utils/streets_service_base/build/streets_service_base_test: error while loading shared libraries: librdkafka.so.1: cannot open shared object file: No such file or directory
CMake Error at /usr/share/cmake-3.22/Modules/GoogleTestAddTests.cmake:83 (message):
  Error running test executable.

    Path: '/home/carma-streets/streets_utils/streets_service_base/build/streets_service_base_test'
    Result: 127
    Output:
```
Here is the link to the CI output for more reference (https://github.com/usdot-fhwa-stol/carma-streets/actions/runs/6881465414/job/18717862054)
I got the idea to add this property from the CMake documentation
"Provides greater control over when gtest_discover_tests() performs test discovery. By default, POST_BUILD sets up a post-build command to perform test discovery at build time. In certain scenarios, like cross-compiling, this POST_BUILD behavior is not desirable. By contrast, PRE_TEST delays test discovery until just prior to test execution. This way test discovery occurs in the target environment where the test has a better chance at finding appropriate runtime dependencies.

DISCOVERY_MODE defaults to the value of the CMAKE_GTEST_DISCOVER_TESTS_DISCOVERY_MODE variable if it is not passed when calling gtest_discover_tests(). This provides a mechanism for globally selecting a preferred test discovery behavior without having to modify each call site."
(https://cmake.org/cmake/help/latest/module/GoogleTest.html)

2023-11-15 22:50 UTC, paulbourelly999 commented on streets_utils/streets_service_base/CMakeLists.txt
> +    DISCOVERY_MODE PRE_TEST
To clarify, this issue finding the librdkafka only occurred when including this `gtest_discover_tests()` instruction and also only occurred in CI and note my local environment. Inspection of the CI shows clearly that librdkafka is installed and in the correct location.

2023-11-16 14:40 UTC, paulbourelly999 commented
There is something wrong with the unit test. Please hold off on merging until I address this.

2023-11-16 15:43 UTC, adamlm requested changes
General comments:

I'm not convinced the mock client/producer/consumer has much utility here. It seems like the `streets_service` only initializes/creates them. After that, users interact with the producer/consumer instances directly. If you want to allow users to user different producer/consumer classes, I think a class template would be better.

There's a lot of dynamic memory allocation hapenning, but I don't see how it's necessary. Do the `kafka_client`, `kafka_consumer_worker`, and `kafka_producer_worker` instances get shared across threads?

2023-11-16 15:43 UTC, adamlm commented on streets_utils/streets_service_base/include/streets_service.h
> +            std::shared_ptr<kafka_clients::kafka_client> _kafka_client;
Why did this get changed to a `std::shared_ptr`? Best practice is to prefer `std::unique_ptr` unless otherwise necessary.

2023-11-16 17:55 UTC, paulbourelly999 commented on streets_utils/streets_service_base/src/streets_service.cpp
> +            _kafka_client = std::make_shared<kafka_clients::kafka_client>();
A unique ptr means that only the streets service can have a reference to the pointer right? Which means my set method would no longer work right. Also this means I could not have an external reference to the mock for setting up EXPECT_CALL and returns for different methods. That is why I made it a shared ptr. Could I get external references to this pointer with unique_ptr

2023-11-16 17:55 UTC, paulbourelly999 commented on streets_utils/streets_service_base/src/streets_service.cpp
> +            _kafka_client = std::make_shared<kafka_clients::kafka_client>();
See below

2023-11-16 17:56 UTC, paulbourelly999 commented on streets_utils/streets_service_base/include/streets_service.h
>              std::shared_ptr<kafka_clients::kafka_consumer_worker> _time_consumer;
See below

2023-11-16 17:56 UTC, paulbourelly999 commented on streets_utils/streets_service_base/include/streets_service.h
> +            std::shared_ptr<kafka_clients::kafka_client> _kafka_client;
See below

2023-11-16 19:28 UTC, adamlm commented on streets_utils/streets_service_base/include/streets_service.h
> +            FRIEND_TEST(test_streets_service, test_start);
Unit tests should be testing the public interface. If I change the implementation details of a function without modifying the function's invariants or contract to the caller, then the unit tests will not need to be modified.

By coupling the unit tests to the implementation details, I will necessarily have to modify the tests even though I shouldn't have to. Making tests friends can easily lead to the unit tests becoming duplicated implementations, which are not proper tests. This is a bit different than white-box/open-box testing. Relying on or requiring friends for unit testing suggests there is a design/architecture flaw.

2023-11-17 00:47 UTC, paulbourelly999 commented on kafka_clients/README.md
>  ```
Hmm can you do that with other code snippets?

2023-11-17 00:49 UTC, paulbourelly999 commented on kafka_clients/README.md
> +This is a library that wraps [librdkafk](https://github.com/confluentinc/librdkafka) C++ kafka client library. It consists of three main classes:
Cool

2023-11-17 00:52 UTC, paulbourelly999 commented on streets_utils/streets_service_base/include/streets_service.h
> +            FRIEND_TEST(test_streets_service, test_start);
I disagree, testing only at the public interface limits the functionality/code you can easily test. I agree that there is a balance in tradeoff between tests that are testing internal functionality and the addition cost of maintaining them. For the most part, it has been my experience that maintain these unit tests is normally worth the additional confidence you can have in you functionality.

2023-11-17 13:45 UTC, paulbourelly999 commented on streets_utils/streets_service_base/CMakeLists.txt
> +    DISCOVERY_MODE PRE_TEST
Still needed the pre_test mode for some reason.

2023-11-17 13:59 UTC, adamlm commented on streets_utils/streets_service_base/src/streets_service.cpp
> +            _kafka_client = std::make_shared<kafka_clients::kafka_client>();
You wouldn't be able to, but the fact that you need to do this in the first place suggests that there is a design flaw. If we plan to revisit the `steets_service`'s design in the future, we can move forward with this approach for now.

2023-11-17 19:55 UTC, adamlm commented on streets_utils/streets_service_base/include/streets_service.h
> +            FRIEND_TEST(test_streets_service, test_start);
After internal discussion, we agreed to keep the friend tests for now and revisit software design/architecture changes that can remove the need for friend tests.

2023-11-17 19:57 UTC, adamlm approved these changes

2023-11-17 19:57 UTC, merged