Dev Container setup for CARMA Streets
usdot-fhwa-stol/carma-streets pull request #368
Opened 2023-11-20 21:45 UTC by paulbourelly999

# PR Details
## Description
Dev Container setup for CARMA Streets

## Related GitHub Issue

## Related Jira Key
[CDAR-389
](https://usdot-carma.atlassian.net/browse/CDAR-389)

## Motivation and Context
Setup easy to use development and integration testing environment

## How Has This Been Tested?
Locally tested both streets_service_base and streets_service_base_lanelet_aware

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [x ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ x] My change requires a change to the documentation.
- [x ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING**](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-11-20 22:33 UTC, adamlm requested changes

2023-11-20 22:33 UTC, adamlm commented on .devcontainer/devcontainer.json
Can we remove commented-out configuration options? Users can look up the Dev Container schema if they are interested.

2023-11-20 22:33 UTC, adamlm commented on .devcontainer/devcontainer.json
> +				"twxs.cmake",
The C/C++ Extension Pack (`ms-vscode.cpptools-extension-pack`) will install all of these together.

2023-11-21 18:44 UTC, paulbourelly999 commented on README.md
> +Docker is the primary deployment mechanism to containerize one or more services. The CARMA Streets application and other major frameworks such as Kafka will run in their own separate containers. This
Add documentation for developing new CS service.

2023-11-21 20:03 UTC, dan-du-car commented on .devcontainer/devcontainer.json
> +		"../docker-compose.yml",
Why do we have two docker-compose.yml file here. Can we rename this docker-compose.yml to docker-compose-devcontainer.yml to indicate its purpose?

2023-11-21 20:04 UTC, dan-du-car commented on .devcontainer/devcontainer.json
> +	"workspaceFolder": "/home/${localWorkspaceFolderBasename}",
What is the value of this localWorkspaceFolderBasename?

2023-11-21 20:04 UTC, dan-du-car commented on .devcontainer/devcontainer.json
> +	// "postCreateCommand": "/home/carma-streets/sensor_data_sharing_service/build.sh",
Is this build.sh needed?

2023-11-21 20:07 UTC, dan-du-car commented on .devcontainer/docker-compose.yml
> +      context: .
Is this context the parent folder using `..`?

2023-11-21 20:08 UTC, dan-du-car commented on .devcontainer/docker-compose.yml
> +  # Uncomment for streets service base lanelet aware dev environment
We can only run one service at a time?

2023-11-21 23:04 UTC, paulbourelly999 commented on .devcontainer/devcontainer.json
> +		"../docker-compose.yml",
Sure

2023-11-21 23:07 UTC, paulbourelly999 commented on .devcontainer/devcontainer.json
> +	"workspaceFolder": "/home/${localWorkspaceFolderBasename}",
It evaluates to the volume setup in the docker-compose-devcontainer.yml to `/home/carma-streets`. Essentially the entire CARMA-Streets repo is copied to home/carma-streets

2023-11-21 23:09 UTC, paulbourelly999 commented on .devcontainer/docker-compose.yml
> +      context: .
The build context here is relative to the project level docker-compose file

2023-11-21 23:09 UTC, paulbourelly999 commented on .devcontainer/docker-compose.yml
> +  # Uncomment for streets service base lanelet aware dev environment
This is a service additional to all other carma-streets service described in the project docker-compose. Please see the added documentation

2023-11-22 14:34 UTC, adamlm commented on .devcontainer/docker-compose-devcontainer.yml
> +    command: /bin/sh -c "while sleep 1000; do :; done"
What is this supposed to do, and why is it necessary?

2023-11-22 14:40 UTC, paulbourelly999 commented on .devcontainer/docker-compose-devcontainer.yml
> +    command: /bin/sh -c "while sleep 1000; do :; done"
This is the command that was provided with the guided creation of a dev container environment. The comment seems to indicate that it prevents the container from shutting down on creation. We use it for our other Dev container setups (https://github.com/usdot-fhwa-OPS/V2X-Hub/blob/774b31fced876b48226302ffd093f66484a76a2f/.devcontainer/docker-compose-vscode.yml#L15).

2023-11-22 14:45 UTC, dan-du-car commented on .devcontainer/devcontainer.json
> +		"../docker-compose.yml",
Can we add comments why we need two docker-compose file?

2023-11-22 14:49 UTC, adamlm commented on .devcontainer/docker-compose-devcontainer.yml
> +    command: /bin/sh -c "while sleep 1000; do :; done"
I don't think this line is actually needed. We use Ubuntu's container as the base image for this. I don't see an `ENTRYPOINT` or `CMD` command in any of the derivative `Dockerfile`s, so this image should use `/bin/sh -c` as its default entry point. What are the "things" that shouldn't shutdown?

2023-11-22 14:53 UTC, dan-du-car approved these changes

2023-11-22 14:53 UTC, paulbourelly999 commented on .devcontainer/docker-compose-devcontainer.yml
> +    command: /bin/sh -c "while sleep 1000; do :; done"
I can try and see if removing this works with our base images but I am against any additional exploring of what commands here work if removing this does not work. I think this is definitely something we could investigate later after more people are using the devcontainer setup. I will try removing it and confirm it work or not  and respond accordingly

2023-11-22 14:58 UTC, paulbourelly999 commented on .devcontainer/docker-compose-devcontainer.yml
> +    command: /bin/sh -c "while sleep 1000; do :; done"
It does not work without. We can investigate this later.

2023-11-22 15:34 UTC, adamlm approved these changes

2023-11-22 15:34 UTC, merged