Fix/ci build
usdot-fhwa-stol/carma-streets pull request #369
Opened 2023-11-22 12:08 UTC by paulbourelly999

# PR Details
## Description

## Related GitHub Issue

## Related Jira Key

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING**](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-11-28 18:46 UTC, adamlm requested changes

2023-11-28 18:46 UTC, adamlm commented on message_services/CMakeLists.txt
> +list(APPEND CMAKE_PREFIX_PATH "/opt/carma/cmake/" "/opt/carma_lanelet2/")
This couples `message_services` to those specific installation directories and forces users to install dependencies there. The project should not dictate where users should have their dependencies. Consider lifting this out of the `CMakeLists.txt` file and putting it where CMake is being invoked. Something like:
```shell
cmake -B build -DCMAKE_PREFIX_PATH="/opt/carma/cmake/;/opt/carma_lanelet2/" .
```
Note the double quotes.

2023-11-28 18:46 UTC, adamlm commented on intersection_model/CMakeLists.txt
> +list(APPEND CMAKE_PREFIX_PATH "/opt/carma/cmake/" "/opt/carma_lanelet2/")
Same comment as below.

2023-11-28 19:42 UTC, dan-du-car commented on .github/workflows/ci.yml
> +            file: ./streets_service_base/Dockerfile
This file path always starts with the root folder where the carma-streets is?

2023-11-28 19:42 UTC, dan-du-car commented on .github/workflows/ci.yml
> +                UBUNTU_CODENAME=${{ matrix.ubuntu-codename }}
Do we need this assignment here UBUNTU_CODENAME?

2023-11-28 19:45 UTC, dan-du-car commented on .github/workflows/ci.yml
> +          tags: usdotfhwastoldev/streets_service_base_lanelet_aware:bionic
maybe replace bionic with ${{ ubuntu-codename }}

2023-11-28 19:46 UTC, dan-du-car commented on .github/workflows/ci.yml
> +      image: usdotfhwastoldev/streets_service_base_lanelet_aware:bionic
The same comments as above if we could use if: ${{ matrix.build_lanelet_aware }}, we may replace the bionic with  ${{ ubuntu-codename }}

2023-11-28 19:46 UTC, dan-du-car commented on .github/workflows/ci.yml
> +        # mkdir /home/carma-streets/.base-image
Do we still need this?

2023-11-28 19:52 UTC, paulbourelly999 commented on .github/workflows/ci.yml
> +      image: usdotfhwastoldev/streets_service_base_lanelet_aware:bionic
No we only have streets_service_base_lanelet_aware supported for bionic currently

2023-11-28 19:53 UTC, paulbourelly999 commented on .github/workflows/ci.yml
> +          tags: usdotfhwastoldev/streets_service_base_lanelet_aware:bionic
No we only have streets_service_base_lanelet_aware suppored for bionic currently

2023-11-28 19:53 UTC, paulbourelly999 commented on .github/workflows/ci.yml
> +            file: ./streets_service_base/Dockerfile
yes

2023-11-28 19:53 UTC, paulbourelly999 commented on .github/workflows/ci.yml
> +            username: ${{ secrets.DOCKERHUB_USERNAME }}
They are only available to admins

2023-11-28 19:54 UTC, paulbourelly999 commented on .github/workflows/ci.yml
> +        # mkdir /home/carma-streets/.base-image
no

2023-11-28 19:57 UTC, paulbourelly999 commented on .github/workflows/ci.yml
> +                UBUNTU_CODENAME=${{ matrix.ubuntu-codename }}
Yes

2023-11-28 20:34 UTC, dan-du-car commented on .github/workflows/ci.yml
> +                UBUNTU_CODENAME=${{ matrix.ubuntu-codename }}
Why? Maybe add some comments?

2023-11-28 20:36 UTC, dan-du-car commented on .github/workflows/ci.yml
> +      image: usdotfhwastoldev/streets_service_base_lanelet_aware:bionic
Can we use this  matrix.build_lanelet_aware flag to set this ${{ ubuntu-codename }} rather than specifically set to bionic.

2023-11-28 20:38 UTC, dan-du-car commented on .github/workflows/ci.yml
> +        # mkdir /home/carma-streets/.base-image
Can we remove the commented out code?

2023-11-28 21:16 UTC, paulbourelly999 commented on .github/workflows/ci.yml
> +      image: usdotfhwastoldev/streets_service_base_lanelet_aware:bionic
There is no reason to build this on multiple ubuntu distros. This CI step is to run the sonar scanner/unit tests. It does not have an artifact and therefore is not worth running multiple times.

2023-11-29 15:34 UTC, adamlm approved these changes

2023-11-29 15:35 UTC, merged