Feature/sdsm generation
usdot-fhwa-stol/carma-streets pull request #373
Opened 2023-12-06 13:51 UTC by paulbourelly999

# PR Details
## Description

## Related GitHub Issue

## Related Jira Key

CDAR-359
## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING**](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-12-08 14:16 UTC, paulbourelly999 commented on docker-compose.yml
> +      KAFKA_CREATE_TOPICS: "v2xhub_scheduling_plan_sub:1:1,v2xhub_bsm_in:1:1,v2xhub_mobility_operation_in:1:1,v2xhub_mobility_path_in:1:1,vehicle_status_intent_output:1:1,v2xhub_map_msg_in:1:1,modifi
probably should add topic for sdsm coming in from V2X-Hub(CDASim) here as well. Not 100 % necessary since kafka broker will create topics on publish attempt but more verbose.

2023-12-08 16:06 UTC, dan-du-car commented on sensor_data_sharing_service/src/detected_object_to_sdsm_converter.cpp
> +        rtn.second = (unsigned int) (posix_time.time_of_day().seconds()*1000 + posix_time.time_of_day().fractional_seconds());
rtn.second or rtn.millisecond?

2023-12-08 16:08 UTC, adamlm requested changes

2023-12-08 16:08 UTC, adamlm commented on sensor_data_sharing_service/src/sensor_data_sharing_service.cpp
> +        catch (const std::exception &ex)
Is there a specific exception that gets thrown? If so, we should catch that one explicitly.

2023-12-08 19:36 UTC, paulbourelly999 commented on sensor_data_sharing_service/src/detected_object_to_sdsm_converter.cpp
> +        rtn.second = (unsigned int) (posix_time.time_of_day().seconds()*1000 + posix_time.time_of_day().fractional_seconds());
The field in SDSM is called second but its units are millisecond. Check the Datetime object in the j2735 spec

2023-12-08 19:37 UTC, paulbourelly999 commented on sensor_data_sharing_service/CMakeLists.txt
> +        ${lanelet2_extension_lib_INCLUDE_DIRS}
Are you sure since I am not using CMake targets. How does this get covered.

2023-12-08 19:41 UTC, paulbourelly999 commented on sensor_data_sharing_service/include/sensor_data_sharing_service.hpp
> +             * @brief Location of sensor. All offsets are interpreted relative to this location.
It's kind of both right. It is its position and it is its coordinate frame origin. I can explicitly say that but its taken from the sensor configured location.

2023-12-08 19:44 UTC, adev4a commented on sensor_data_sharing_service/src/detected_object_to_sdsm_converter.cpp
> +        rtn._detected_object_common_data._speed = (unsigned int) std::hypot( msg._velocity._x* 50,  msg._velocity._y* 50);
Can we declare these hardcoded values as constants instead?

2023-12-08 19:45 UTC, paulbourelly999 commented on sensor_data_sharing_service/src/sensor_configuration_parser.cpp
> +            for (auto itr = doc.Begin(); itr != doc.End(); ++itr) {
Yep that is intended.

2023-12-08 19:46 UTC, paulbourelly999 commented on sensor_data_sharing_service/test/detected_object_to_sdsm_converter_test.cpp
> +        EXPECT_EQ((unsigned int) (msg._size._length*10), std::get<streets_utils::messages::sdsm::detected_obstacle_data>(data._detected_object_optional_data.value())._size._length);
What is the difference?

2023-12-08 19:49 UTC, paulbourelly999 commented on sensor_data_sharing_service/src/sensor_data_sharing_service.cpp
> +            msg._objects.push_back(detected_object_data);
Check the TODO comment. we need to update the offset of the detection using the sdsm timestamp eventually. Currently there is a bug that detected objects at carma-streets do not have a timestamp information so that will be done once the bug is fixed.  Technically I could include it in the to_detected_object_data call if I pass in timestamp but I think it also makes sense to do it separately.

2023-12-08 19:50 UTC, paulbourelly999 commented on coverage.sh
> +source /opt/ros/melodic/setup.bash
This service uses lanelet2, a forked version built from our autoware.ai repository. We currently only have build scripts that work using ros1 to build lanelet2.(lanelet2 i think requires ros or atleast parts of it.)

2023-12-08 19:52 UTC, paulbourelly999 commented on sensor_data_sharing_service/src/detected_object_to_sdsm_converter.cpp
> +        rtn._detected_object_common_data._speed = (unsigned int) std::hypot( msg._velocity._x* 50,  msg._velocity._y* 50);
You mean the unit translations. Yeah I think that is a good idea.

2023-12-08 19:57 UTC, paulbourelly999 commented on sensor_data_sharing_service/CMakeLists.txt
> +        ${lanelet2_extension_lib_INCLUDE_DIRS}
```cmake
set(depends "lanelet2_core;lanelet2_io;lanelet2_maps;lanelet2_projection;lanelet2_routing;lanelet2_traffic_rules;lanelet2_validation;hardcoded_params")
foreach(depend ${depends})
  string(REPLACE " " ";" depend_list ${depend})
  # the package name of the dependency must be kept in a unique variable so that it is not overwritten in recursive calls
  list(GET depend_list 0 lanelet2_extension_dep)
  list(LENGTH depend_list count)
  if(${count} EQUAL 1)
    # simple dependencies must only be find_package()-ed once
    if(NOT ${lanelet2_extension_dep}_FOUND)
      find_package(${lanelet2_extension_dep} REQUIRED NO_MODULE)
    endif()
  else()
    # dependencies with components must be find_package()-ed again
    list(REMOVE_AT depend_list 0)
    find_package(${lanelet2_extension_dep} REQUIRED NO_MODULE ${depend_list})
  endif()
  _list_append_unique(lanelet2_extension_INCLUDE_DIRS ${${lanelet2_extension_dep}_INCLUDE_DIRS})
```

2023-12-08 20:10 UTC, paulbourelly999 commented on sensor_data_sharing_service/src/detected_object_to_sdsm_converter.cpp
> +        streets_utils::messages::sdsm::time_stamp rtn;
I do not agree with the first sentence but I do agree this variable is poorly named. It was a place holder name for return(rtn)

2023-12-08 20:10 UTC, paulbourelly999 commented on sensor_data_sharing_service/src/detected_object_to_sdsm_converter.cpp
> +        streets_utils::messages::sdsm::time_stamp rtn;
I will address this.

2023-12-08 20:11 UTC, paulbourelly999 commented on sensor_data_sharing_service/src/detected_object_to_sdsm_converter.cpp
> +        rtn.second = (unsigned int) (posix_time.time_of_day().seconds()*1000 + posix_time.time_of_day().fractional_seconds());
Is this the reasoning (https://stackoverflow.com/questions/475824/static-castintfoo-vs-intfoo)

2023-12-08 20:11 UTC, paulbourelly999 commented on sensor_data_sharing_service/src/detected_object_to_sdsm_converter.cpp
> +            optional_data._vehicle_height = (unsigned int) (msg._size._height * 20);
See comment above.

2023-12-08 20:11 UTC, paulbourelly999 commented on sensor_data_sharing_service/src/detected_object_to_sdsm_converter.cpp
> +            rtn._detected_object_optional_data = optional_data;
I do not know what you mean. I am populating the SDSM

2023-12-08 20:17 UTC, paulbourelly999 commented on sensor_data_sharing_service/src/sensor_configuration_parser.cpp
> +            throw std::runtime_error("Encounter document parse error while attempting to parse sensor configuration file " + filepath + "!");
SPDLOG Is coupled to all our libraries since it is our logging library. Yeah we could return a bunch of weird stuff and rely on users to translate that into log statements to make our service more log library agnostic but it suffer in usability then in my opinion. To me being log library agnostic is not a terribly high priority concern. I do agree that having a log statement right before throwing an exception seems weird, I may add a custom exception takes in a rapidjson Document and appends that to the log statement.

2023-12-10 23:37 UTC, adev4a commented on sensor_data_sharing_service/include/sensor_configuration_parser.hpp
> +     * @brief Method to parse sensor configuration json file.
Can we add to the description that this function is responsible for retrieving the location of the sensor? 
I know that the return description does mention that, but it would be nice for the brief to indicate the same.

2023-12-10 23:37 UTC, adev4a commented on sensor_data_sharing_service/src/detected_object_to_sdsm_converter.cpp
> +        // Milliseconds of the current minute. The SDMS field is named seconds but is in the unit of milliseconds (see DDateTime from J2735).
Should say SD"SM" field

2023-12-10 23:37 UTC, adev4a commented on sensor_data_sharing_service/src/detected_object_to_sdsm_converter.cpp
> +        rtn.second = (unsigned int) (posix_time.time_of_day().seconds()*1000 + posix_time.time_of_day().fractional_seconds());
Is ptime.fractional_seconds in milliseconds? Seems like its nanoseconds as defined here https://boost.sourceforge.net/regression-logs/cs-win32_metacomm/doc/html/date_time.posix_time.html#date_time.posix_time.ptime_class

2023-12-10 23:37 UTC, adev4a commented on sensor_data_sharing_service/src/sensor_configuration_parser.cpp
> +                    sensor_location = lanelet::BasicPoint3d{
Just to make sure, this will make sure we are not returning a partially populated BasicPoint3d right?

2023-12-10 23:37 UTC, adev4a commented on sensor_data_sharing_service/src/sensor_data_sharing_service.cpp
> +            this->map_projector = std::make_unique<lanelet::projection::LocalFrameProjector>(target_frame.c_str());
Are map_projector and map_ptr only being used locally here? Do they need to be class members?

2023-12-11 18:20 UTC, paulbourelly999 commented on sensor_data_sharing_service/src/detected_object_to_sdsm_converter.cpp
> +        // Milliseconds of the current minute. The SDMS field is named seconds but is in the unit of milliseconds (see DDateTime from J2735).
Good catch

2023-12-11 18:39 UTC, adamlm commented on sensor_data_sharing_service/src/sensor_data_sharing_service.cpp
> +            msg._objects.push_back(detected_object_data);
Yeah that's fine. I assumed this part of the code was likely to change soon

2023-12-11 19:27 UTC, adamlm requested changes

2023-12-11 19:27 UTC, adamlm commented on sensor_data_sharing_service/test/detected_object_to_sdsm_converter_test.cpp
> +        EXPECT_EQ((unsigned int) (msg._size._length*10), std::get<streets_utils::messages::sdsm::detected_obstacle_data>(data._detected_object_optional_data.value())._size._length);
`(unsigned int)` is a C-style cast. Here's some more information on the difference:
https://stackoverflow.com/questions/1609163/what-is-the-difference-between-static-cast-and-c-style-casting

2023-12-11 19:53 UTC, paulbourelly999 commented on sensor_data_sharing_service/src/sensor_configuration_parser.cpp
> +                    sensor_location = lanelet::BasicPoint3d{
Is there a specific field I am not populating?

2023-12-11 19:55 UTC, paulbourelly999 commented on sensor_data_sharing_service/src/sensor_data_sharing_service.cpp
> +            this->map_projector = std::make_unique<lanelet::projection::LocalFrameProjector>(target_frame.c_str());
We need the map projector for getting the WSG84 location of the sensor from cartesian coordinates

2023-12-11 20:23 UTC, paulbourelly999 commented on sensor_data_sharing_service/src/detected_object_to_sdsm_converter.cpp
> +        rtn.second = (unsigned int) (posix_time.time_of_day().seconds()*1000 + posix_time.time_of_day().fractional_seconds());
No its microseconds by default. It corresponds to the resolution field

2023-12-11 20:52 UTC, paulbourelly999 commented
@adev4a This is the enhancement for improving our inclusion of the lanelet2 libraries

2023-12-11 22:16 UTC, adamlm approved these changes

2023-12-11 22:17 UTC, merged