CDAR-790:Fix kafka data collection script
usdot-fhwa-stol/carma-streets pull request #397
Opened 2024-02-14 13:53 UTC by paulbourelly999

+ update script to consume data from new topics

# PR Details
## Description

## Related GitHub Issue

## Related Jira Key

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING**](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-02-14 18:40 UTC, adamlm requested changes

2024-02-14 18:40 UTC, adamlm commented on collect_kafka_logs.py
> +    parser.add_argument('outfile', help='Folder name for the resulting folder logs are placed in', type=str)  # Required argument
Can we update `outfile` to `outdir` since the parameter is no longer a filename?

2024-02-14 19:38 UTC, dan-du-car commented on docker-compose.yml
>        WAIT_HOSTS: localhost:8080
maybe remove the wait hosts if we use docker service health check

2024-02-20 17:19 UTC, paulbourelly999 commented on docker-compose.yml
>        WAIT_HOSTS: localhost:8080
We should create a separate enhancement to replace other checks with docker health check.

2024-02-20 18:53 UTC, paulbourelly999 commented on collect_kafka_logs.py
> +    parser.add_argument('outfile', help='Folder name for the resulting folder logs are placed in', type=str)  # Required argument
Resolved

2024-02-20 19:00 UTC, paulbourelly999 commented on collect_kafka_logs.py
> +#  Copyright (C) 2018-2020 LEIDOS.
Resolved

2024-02-20 19:04 UTC, paulbourelly999 commented on docker-compose.yml
>        WAIT_HOSTS: localhost:8080
Created the following issue to track replacing docker compose wait with health checks (https://github.com/usdot-fhwa-stol/carma-streets/issues/398)

2024-02-20 19:17 UTC, adamlm requested changes

2024-02-20 19:17 UTC, adamlm commented on collect_kafka_logs.py
> +        os.system(f'rm -r {outfile}')
The `shutil` package is preferred over `os` for file operations in modern Python. Can we replace these lines with the `shutil` equivalents?

2024-02-20 19:17 UTC, adamlm commented on collect_service_logs.sh
There are two ShellCheck issues about double quotes. Can we resolve these?
```
In script.sh line 105:
    zip -rq ./${output}.zip ./scheduling_service/logs ./intersection_model/logs ./tsc_client_service/logs ./message_services/logs ./signal_opt_service/logs ./sensor_data_sharing_service/logs
              ^-------^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
    zip -rq ./"${output}".zip ./scheduling_service/logs ./intersection_model/logs ./tsc_client_service/logs ./message_services/logs ./signal_opt_service/logs ./sensor_data_sharing_service/logs


In script.sh line 109:
    zip -rq ./${filename}.zip ./scheduling_service/logs ./intersection_model/logs ./tsc_client_service/logs ./message_services/logs ./signal_opt_service/logs ./sensor_data_sharing_service/logs
              ^---------^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
    zip -rq ./"${filename}".zip ./scheduling_service/logs ./intersection_model/logs ./tsc_client_service/logs ./message_services/logs ./signal_opt_service/logs ./sensor_data_sharing_service/logs

For more information:
  https://www.shellcheck.net/wiki/SC2086 -- Double quote to prevent globbing ...
```

2024-02-20 19:20 UTC, paulbourelly999 commented on collect_service_logs.sh
Addressed

2024-02-20 19:36 UTC, paulbourelly999 commented on collect_kafka_logs.py
> +        os.system(f'rm -r {outfile}')
I think we should add this as an enhancement. While it may offer some benefits for maintainability, I am hesitant to delay this issue for this. There are several other references to os. that I did not write that I may require some effort to translate.

2024-02-21 00:52 UTC, dan-du-car commented on README.md
> +  --topics TOPICS [TOPICS ...]
Is this topics list comma separated string?

2024-02-21 00:56 UTC, dan-du-car commented on README.md
> +options:
Can we add description to usage or somewhere to note what services logs this script is going to collect and zip? Please update the readme as well to list the supported services.

2024-02-21 00:59 UTC, dan-du-car commented on README.md
> +  -h, --help            show this help message and exit
Does this -h also print the options and their descriptions? The same comment for zip service logs script

2024-02-21 14:43 UTC, paulbourelly999 commented on README.md
> +  -h, --help            show this help message and exit
yes

2024-02-21 14:52 UTC, paulbourelly999 commented on README.md
> +options:
Right above this I mention that is collects "all CARMA Street service logs". I think this is probably sufficient documentation

2024-02-21 16:02 UTC, adamlm requested changes

2024-02-21 16:02 UTC, adamlm commented on collect_kafka_logs.py
> +    elif os.path.isfile(f'{os.getcwd()}/{outdir}.zip'):
Same comment about `pathlib`:
```python
from pathlib import Path

# other code ...

if Path(Path.cwd() / f"{outdir}.zip").is_file():
    # ...

2024-02-21 16:02 UTC, adamlm commented on collect_kafka_logs.py
> +    os.system(f'mkdir {outdir}')
`pathlib` can also make directories:
```python
from pathlib import Path

# other code ...

Path.mkdir(exist_ok=True)
```

2024-02-21 16:04 UTC, adamlm commented on collect_kafka_logs.py
> +        os.system(f'rm -r {outfile}')
If the PR changes didn't touch the related code, I would agree. I requested additional changes that replace relevant `os` calls with the modern `pathlib` alternative. The only remaining `os` references are related to (sub)process management.

2024-02-21 17:50 UTC, paulbourelly999 commented on collect_kafka_logs.py
> +    if os.path.isdir(f'{os.getcwd()}/{outdir}'):
Resolved.

2024-02-21 17:50 UTC, paulbourelly999 commented on collect_kafka_logs.py
> +    elif os.path.isfile(f'{os.getcwd()}/{outdir}.zip'):
Resolved

2024-02-21 17:51 UTC, paulbourelly999 commented on collect_kafka_logs.py
> +    os.system(f'mkdir {outdir}')
resolved

2024-02-21 18:12 UTC, paulbourelly999 commented on collect_kafka_logs.py
> +        os.system(f'rm -r {outfile}')
Resolve

2024-02-21 18:28 UTC, paulbourelly999 commented on collect_kafka_logs.py
> +    elif Path(Path.cwd()/f'{outdir}.zip').is_dir():
Resolved

2024-02-21 19:06 UTC, merged