updated config to build and push other services
usdot-fhwa-stol/carma-streets pull request #41
Opened 2021-11-16 13:49 UTC by SaikrishnaBairamoni

# PR Details
Included intersection model and message services to build
## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
[CARMA Contributing Guide](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) 
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-11-16 17:35 UTC, paulbourelly999 requested changes
Almost everything looks good. Checkout the sonar-properties file.

2021-11-16 17:35 UTC, paulbourelly999 commented on .sonarqube/sonar-scanner.properties
> +intersection_model.tests=test
I think the propert is called intersection_model.sonar.test=test. Please update for all modules

2021-11-16 17:35 UTC, paulbourelly999 commented on intersection_model/src/server/src/models/OAILanelet_info.cpp
> +    }
Why was this necessary. Was there a bug in the intersection model.

2021-11-17 16:21 UTC, paulbourelly999 commented on .circleci/config.yml
> +            source /opt/ros/melodic/setup.bash && \
You need to source this file as well! 
/home/carma-streets/carma_lanelet2/install/setup.bash

2021-11-17 16:53 UTC, dan-du-car commented on intersection_model/src/server/src/models/OAILanelet_info.cpp
> +    }
Remove the update for this file.

2021-12-28 17:42 UTC, paulbourelly999 commented on .circleci/config.yml
> +            source /opt/ros/melodic/setup.bash && \
please add `&& source /home/carma-streets/carma_lanelet2/install/setup.bash` and see if that fixes the issue

2022-01-04 19:54 UTC, dan-du-car commented on .circleci/config.yml
> +      - docker_build_push_develop_scheduling_service:
Not sure why we need to add separate filters for develop branch both only and ignore.

2022-01-04 20:03 UTC, paulbourelly999 commented on .circleci/config.yml
> +      - docker_build_push_develop_scheduling_service:
Because of image tags. All images are tagged with branch name except develop which is tagged with latest. We do the same thing for V2X-Hub. If you think its cleaner to have a single job that has an if check for branch name and creates a different tag name for develop I can look into that but functionally I would not make any difference.

2022-01-04 20:03 UTC, paulbourelly999 approved these changes

2022-01-04 20:05 UTC, dan-du-car commented on coverage.sh
> +mv *.gcov coverage
Is this report supposed to reflect in the sonarcloud? The sonarcloud coverage is not updated.

2022-01-04 20:11 UTC, SaikrishnaBairamoni commented on coverage.sh
> +mv *.gcov coverage
Yes, Once we merge this PR to main branch(develop) we can see the new report on sonar cloud, But we need to check and make changes if coverage reports are not generated after merging.

2022-01-04 20:18 UTC, paulbourelly999 commented on coverage.sh
> +mv *.gcov coverage
Correct, sonar-scanner only runs code analysis ( static and coverage ) on new code for PRs. It will only run a complete scan on our main configured branch, which is currently develop. Once we merge this we will be able to tell whether my changes fix our code coverage reports issues and potentially what our current code unit test coverage is.

2022-01-04 22:39 UTC, dan-du-car approved these changes

2022-01-04 22:39 UTC, merged