413: Fix sensor_data_sharing unit test
usdot-fhwa-stol/carma-streets pull request #414
Opened 2024-04-08 18:54 UTC by paulbourelly999

# PR Details
## Description
There was a unit test in the `sensor_data_sharing_service` that started failing on the release candidate. The issue seemed to be that the `int` data type was to small for a delay we were measuring, which caused the number to wrap to a negative number. This negative delay value pushed us unintentionally into a different condition causing the unit test to fail. Below are logs from the failing test case before the changes:
```
[2024-04-08 18:54:18.228] [debug] [streets_service.cpp:136] Reading system config SIMULATION_MODE as : FALSE!
[2024-04-08 18:54:18.228] [info] [streets_singleton.tpp:27] Initializing Singleton of type PN9fwha_stol3lib4time10CarmaClockE!
[2024-04-08 18:54:18.228] [info] [streets_service.cpp:21] Initializing sensor_data_sharing_service streets service in simulation mode : false!
[2024-04-08 18:54:18.228] [warning] [streets_service.cpp:141] System config LOGS_DIRECTORY was not set! Using default value ../logs/!
[2024-04-08 18:54:18.228] [debug] [sensor_data_sharing_service.cpp:41] Intializing Sensor Data Sharing Service
[2024-04-08 18:54:18.228] [debug] [streets_service.cpp:136] Reading system config LANELET2_MAP as : /home/carma-streets/MAP/Intersection.osm!
[2024-04-08 18:54:18.228] [error] [sensor_data_sharing_service.cpp:82] Cannot read osm file /home/carma-streets/MAP/Intersection.osm. Error message: In function parseMapParams:
Errors occured while parsing .osm file: File was not found .
[2024-04-08 18:54:18.228] [error] [sensor_data_sharing_service.cpp:44] Failed to read lanlet2 map /home/carma-streets/MAP/Intersection.osm !
[2024-04-08 18:54:18.229] [debug] [sensor_data_sharing_service.cpp:91] Attempting to consume detections ...
[2024-04-08 18:54:18.229] [error] [sensor_data_sharing_service.cpp:133] Exception occured consuming detection message : Message JSON is misformatted. JSON parsing failed!
/home/carma-streets/sensor_data_sharing_service/test/sensor_data_sharing_service_test.cpp:92: Failure
Expected equality of these values:
  serv.detected_objects.size()
    Which is: 1
  0

GMOCK WARNING:
Uninteresting mock function call - returning directly.
    Function call: stop()
NOTE: You can safely ignore the above warning unless this call should not happen.  Do not suppress it by blindly adding an EXPECT_CALL() if you don't mean to enforce the call.  See https://github.com/google/googletest/blob/main/docs/gmock_cook_book.md#knowing-when-to-expect-useoncall for details.
[  FAILED  ] sensorDataSharingServiceTest.consumeDetections (3 ms)
[----------] 1 test from sensorDataSharingServiceTest (3 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (3 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] sensorDataSharingServiceTest.consumeDetections

 1 FAILED TEST
[2024-04-08 18:54:18.229] [debug] [sensor_data_sharing_service.cpp:101] Detection Delay : -1089493875ms!
[2024-04-08 18:54:18.229] [warning] [sensor_data_sharing_service.cpp:120] Skipping incoming detection. Current time is 1712602458229ms and detection time stamp is 1000ms. 
                                Sensor Data Sharing Service and sensor producing detections to not appear to be time synchronized.
[2024-04-08 18:54:18.229] [debug] [sensor_data_sharing_service.cpp:128] Detected Object List Size 1 after consumed: 
                                                                    {
                                                                        "type":"CAR",
                                                                        "confidence":0.7,
                                                                        "sensorId":"sensor1",
                                                                        "projString":"projectionString2",
                                                                        "objectId":123,
                                                                        "position":{
                                                                            "x":-1.1,
                                                                            "y":-2.0,
                                                                            "z":-3.2
                                                                        },
                                                                        "positionCovariance":[[1.0,0.0,0.0],[1.0,0.0,0.0],[1.0,0.0,0.0]],
                                                                        "velocity":{
                                                                            "x":1.0,
                                                                            "y":1.0,
                                                                            "z":1.0
                                                                        },
                                                                        "velocityCovariance":[[1.0,0.0,0.0],[1.0,0.0,0.0],[1.0,0.0,0.0]],
                                                                        "angularVelocity":{
                                                                            "x":0.1,
                                                                            "y":0.2,
                                                                            "z":0.3
                                                                        },
                                                                        "angularVelocityCovariance":[[1.0,0.0,0.0],[1.0,0.0,0.0],[1.0,0.0,0.0]],
                                                                        "size":{
                                                                            "length":2.0,
                                                                            "height":1.0,
                                                                            "width":0.5
                                                                        },
                                                                        "timestamp":1000
                                                                    }
                                                                    
[2024-04-08 18:54:18.229] [error] [sensor_data_sharing_service.cpp:136] Something went wrong, no longer consuming detections.
[2024-04-08 18:54:18.229] [warning] [sensor_data_sharing_service.cpp:31] Stopping Detection consumer!
[2024-04-08 18:54:18.229] [info] [streets_service.cpp:7] Destructor called for streets service sensor_data_sharing_service!
```

## Related GitHub Issue
#413 

## Related Jira Key

## Motivation and Context
Fix unit test 

## How Has This Been Tested?
Unit testing 

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING**](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-04-08 19:14 UTC, MishkaMN submitted a review, later dismissed

2024-04-08 19:42 UTC, adamlm requested changes

2024-04-08 19:42 UTC, adamlm commented on sensor_data_sharing_service/src/sensor_data_sharing_service.cpp
> +                    auto delay = static_cast<uint64_t>(ss::streets_clock_singleton::time_in_ms()) - static_cast<uint64_t>(detected_object._timestamp);
The return type for `time_in_ms()` and the type for `_timestamp` are both `std::uint64_t`, so we don't need to cast here.

Another thing to note is that we're not checking for a rollover in case the object's timestamp is lager than the service's clock.

2024-04-08 19:48 UTC, paulbourelly999 commented on sensor_data_sharing_service/src/sensor_data_sharing_service.cpp
> +                    auto delay = static_cast<uint64_t>(ss::streets_clock_singleton::time_in_ms()) - static_cast<uint64_t>(detected_object._timestamp);
Sorry I should have cast to int64. The idea is that we could get a negative number as well if detected_object.timestamp is larger than time_in_ms()_

2024-04-08 20:01 UTC, MishkaMN commented on sensor_data_sharing_service/src/sensor_data_sharing_service.cpp
> +                    auto delay = static_cast<uint64_t>(ss::streets_clock_singleton::time_in_ms()) - static_cast<uint64_t>(detected_object._timestamp);
Dismissed my earlier approval realizing it needed to be signed ints

2024-04-08 20:13 UTC, MishkaMN requested changes

2024-04-08 20:13 UTC, MishkaMN commented on sensor_data_sharing_service/src/sensor_data_sharing_service.cpp
> -                        ss::streets_clock_singleton::sleep_for(abs(delay));
if the delay can be negative, then we should keep the abs here right?

2024-04-08 20:34 UTC, MishkaMN submitted a review, later dismissed

2024-04-19 14:10 UTC, adamlm submitted a review, later dismissed

2024-04-29 15:31 UTC, MishkaMN approved these changes

2024-05-29 17:54 UTC, merged