Issue with ubuntu bionic
usdot-fhwa-stol/carma-streets pull request #422
Opened 2024-08-02 13:00 UTC by dan-du-car

# PR Details
## Description

## Related GitHub Issue

## Related Jira Key

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING**](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-08-20 18:22 UTC, dan-du-car commented
@paulbourelly999  It is ready for review.

2024-08-21 13:51 UTC, paulbourelly999 commented on streets_service_base_lanelet_aware/Dockerfile
> +RUN cat /opt/carma-streets/build_scripts/install_lanelet2_dependencies.sh
this looks like a mistake or a logging left over line. Can it be removed

2024-08-21 13:58 UTC, paulbourelly999 commented on .github/workflows/feature_branch.yml
Last thing that might be good to explore under this PR. We have a step titled `Install newer git for checkout` which is intended to install a newer version of the git cli to be used with out `checkout` action. It seems this was only added since bionic comes with a very old version of git. Could we remove this step now that we are using focal and see if everything still works?

2024-08-21 13:58 UTC, paulbourelly999 requested changes
Some very small changes

2024-08-21 18:16 UTC, paulbourelly999 approved these changes

2024-08-21 18:29 UTC, merged