Update GitHub Actions Third-Party Action Versions
usdot-fhwa-stol/carma-streets pull request #431
Opened 2024-11-07 19:48 UTC by SaikrishnaBairamoni

# PR Details
Update GitHub Actions workflows with latest version of third party actions from external repositories to remove deprecation warnings .
## Description

## Related GitHub Issue

## Related Jira Key
[ARC-250](https://usdot-carma.atlassian.net/browse/ARC-250)

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [x] Defect fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [x] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING**](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

[ARC-250]: https://usdot-carma.atlassian.net/browse/ARC-250?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-11-12 13:13 UTC, paulbourelly999 commented
@SaikrishnaBairamoni  there still seems to be a warning in the build workflow for the setup-java actions (https://github.com/usdot-fhwa-stol/carma-streets/actions/runs/11730232693). Can we upgrade this as well in this PR?

2024-11-12 13:14 UTC, paulbourelly999 requested changes
Try to also update the setup-java action to see if we can remove all deprecated git hub actions from carma-streets CI

2024-11-12 15:19 UTC, dan-du-car submitted a review, later dismissed

2024-11-13 17:13 UTC, paulbourelly999 approved these changes

2024-11-13 17:14 UTC, merged