Osm update
usdot-fhwa-stol/carma-streets pull request #46
Opened 2021-11-19 21:16 UTC by Saeid-Solei

# PR Details
The "osm" header file is removed. Instead, the "intersection_client" header file is added. This new header file will get the intersection information from the intersection model REST API.

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
[CARMA Contributing Guide](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) 
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-11-22 18:37 UTC, paulbourelly999 requested changes

2021-11-22 18:37 UTC, paulbourelly999 commented on scheduling_service/src/intersection_client.cpp
> +              // qDebug() << "entry lanelet ID: "   << itr->getId();
replace this log statements with SPD log statements. You can uncomment them and leave them at the debug level. That way they will only print when we set the loglevel to debug

2021-11-22 18:37 UTC, paulbourelly999 commented on scheduling_service/src/intersection_client.cpp
> +              li.speed_limit = itr->getSpeedLimit() * 0.44704;
When doing a unit conversion include a comment about unit conversion. From what to what.

2021-11-22 18:37 UTC, paulbourelly999 commented on scheduling_service/src/intersection_client.cpp
> +              // if (li.direction == "straight"){
What is this ??

2021-11-22 18:37 UTC, paulbourelly999 commented on scheduling_service/src/main.cpp
> +            for (int m = 0; m < (int)listRDV.size(); ++m) {
Why do you have to cast this. Doesn't size return an int. Just curious

2021-11-22 18:37 UTC, paulbourelly999 commented on scheduling_service/test/test_intersection_client.cpp
> +    /* this unit test is conducted for the west intersection at TFHRC */
Does this unit test need the server to be running? Can we mock the server

2021-11-22 18:51 UTC, Saeid-Solei commented on scheduling_service/CMakeLists.txt
> -target_link_libraries(${BINARY} PUBLIC  ${PROJECT_NAME}_lib Boost::system kafka_clients_lib rdkafka++ Boost::thread spdlog::spdlog gtest)
Yes, it seems like that. I got some errors when I wanted to include the intersection_client header file in other scheduling_service header files. Dan suggested these changes which fixed the problem.

2021-11-22 18:52 UTC, Saeid-Solei commented on scheduling_service/Dockerfile
> +RUN apt-get update  && apt-get install -y cmake libboost1.65-all-dev git autotools-dev automake sqlite3 libsqlite3-dev curl libpugixml-dev libgeographic-dev qtbase5-dev qtbase5-dev-tools libqhttpengi
Actually, I am not sure. This is part of the changes Dan suggested.

2021-11-22 18:56 UTC, Saeid-Solei commented on scheduling_service/src/intersection_client.cpp
> +              // if (li.direction == "straight"){
So, the way we used to define the priority of each link was based on the lane's direction. But since the direction information of the link lanelets is not available, we cannot prioritize the link lanelets based on their directions. Therefore, I commented it for now and assigned the same priority for all link lanelets.

2021-11-22 18:57 UTC, Saeid-Solei commented on scheduling_service/src/main.cpp
> +            for (int m = 0; m < (int)listRDV.size(); ++m) {
For some reason, .size() returns u_int64_t. Therefore, we received some warnings when running make. I made these changes to get rid of the warnings.

2021-11-23 04:30 UTC, paulbourelly999 requested changes

2021-11-23 04:30 UTC, paulbourelly999 commented on .circleci/config.yml
Still need to add steps to install the intersection model client Dan created in circle ci

2021-11-23 04:30 UTC, paulbourelly999 commented on scheduling_service/Dockerfile
> +COPY ./streets_utils/ /home/carma-streets/streets_utils
Docker build is still failing. We need to fix that as well

2021-11-23 16:08 UTC, Saeid-Solei commented on scheduling_service/src/intersection_client.cpp
> +              // qDebug() << "entry lanelet ID: "   << itr->getId();
Done!

2021-11-23 16:10 UTC, Saeid-Solei commented on scheduling_service/test/test_intersection_client.cpp
> +    /* this unit test is conducted for the west intersection at TFHRC */
Yes, it needs the intersection_model to be running. We probably should mock the intersection_model.

2021-11-30 14:39 UTC, dan-du-car commented on .circleci/config.yml
```
cd streets_utils/streets_api/intersection_client_api
mkdir build
cmake .. && make
make install
rm -r build
```

2021-11-30 14:40 UTC, dan-du-car commented on .circleci/config.yml
This above is the command.

2021-11-30 14:47 UTC, dan-du-car commented on scheduling_service/Dockerfile
> +COPY ./streets_utils/ /home/carma-streets/streets_utils
Add the street_utils installation here: https://github.com/usdot-fhwa-stol/carma-streets/blob/76c2e61a758af0fe9cc7ad609618160e141e5618/build.sh#L25

2021-11-30 14:52 UTC, dan-du-car commented on scheduling_service/src/intersection_client.cpp
> +              // if (li.direction == "straight"){
remove it if not needed

2021-11-30 14:58 UTC, dan-du-car commented on scheduling_service/src/intersection_client.cpp
> +              li.direction = "straight";
- Why we cannot decide which vehicle to go based on first-in-first-out? 

- What is the current priority based on? direction and ?

2021-11-30 15:32 UTC, Saeid-Solei commented on scheduling_service/src/intersection_client.cpp
> +              li.direction = "straight";
what shall we use instead of "straight"?

2021-11-30 15:33 UTC, Saeid-Solei commented on scheduling_service/src/intersection_client.cpp
> +              li.direction = "straight";
the scheduling algorithm decides the departure sequence such that the average delay decreases. The departure sequence will not always follow first-in-first-out.

2021-11-30 15:34 UTC, Saeid-Solei commented on scheduling_service/src/intersection_client.cpp
> +              // if (li.direction == "straight"){
Let keep it in case if the lane directions become available later.

2021-11-30 16:40 UTC, Saeid-Solei commented on .circleci/config.yml
Done!

2021-11-30 16:41 UTC, Saeid-Solei commented on scheduling_service/Dockerfile
> +COPY ./streets_utils/ /home/carma-streets/streets_utils
Done!

2021-11-30 16:41 UTC, Saeid-Solei commented on scheduling_service/src/intersection_client.cpp
> +              li.speed_limit = itr->getSpeedLimit() * 0.44704;
I removed the direction for now.

2021-11-30 16:44 UTC, dan-du-car commented on scheduling_service/Dockerfile
> +RUN apt-get update  && apt-get install -y cmake libboost1.65-all-dev git autotools-dev automake sqlite3 libsqlite3-dev curl libpugixml-dev libgeographic-dev qtbase5-dev qtbase5-dev-tools libqhttpengi
I guess we just copied the same from message_services

2021-11-30 16:46 UTC, dan-du-car commented on scheduling_service/CMakeLists.txt
> -target_link_libraries(${BINARY} PUBLIC  ${PROJECT_NAME}_lib Boost::system kafka_clients_lib rdkafka++ Boost::thread spdlog::spdlog gtest)
> 

I think the same as this.

2021-11-30 17:10 UTC, merged